### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by NetsuiteBitch** [dotintent/react-native-ble-plx#1004]
## Expected Behavior

`discoverAllServicesAndCharacteristicsForDevice(device.id).then(device => device.services()) `

returns an array of services.

## Current Behavior

`device.services()` returns a specific object ` {"_U": 0, "_V": 0, "_W": null, "_X": null}`

What is the current behavior?

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Here is the code I am using.

```
        this.manager.stopDeviceScan();
        this.manager
          .connectToDevice(device.id, {autoConnect: true, refreshGatt: false})
          .then(device => {
            (async () => {
              console.log('connected to ', {device});
              this.manager.discoverAllServicesAndCharacteristicsForDevice(device.id).then(x => {
                console.log('discovered services and characteristics', x);
                console.log('discovered services and characteristics', x.services());
              })
              device.onDisconnected((error, disconnectedDevice) => {
                console.log('Disconnected ', disconnectedDevice.name);
                this.scanAndConnect();
              });
            })();
          });
```

### Context

Platform: Android

On the latest version, I can see the service using the NRF connect app.

**Comment by dominik-czupryna-withintent** [comment]
{"_U": 0, "_V": 0, "_W": null, "_X": null} is unresolved promise 
And you're probably making a mistake in an asynchronous function in the promise chain
