### ISSUE TITLE
Question - compatibility with newer react-native versions

### ISSUE THREAD

**Issue by owav** [dotintent/react-native-ble-plx#1006]
Hi,

The compatibility info in the readme stops at react-native 0.63.3.
What is the compatibility status with newer versions (e.g. 0.69.x) ?

Did someone here had success (or not) with newer react-native versions ?
It works for me with RN 0.66.4, but I don't manage to make it work with RN 0.69.5

**Comment by josmas** [comment]
Works with RN 0.68.2, but have not tried 0.69.

**Comment by dominik-czupryna-withintent** [comment]
Version 3.0.0 has been tested using the latest versions of RN and everything should be fine.
