### ISSUE TITLE
Expo app crashes immediately if BleManager is used

### ISSUE THREAD

**Issue by t3db0t** [dotintent/react-native-ble-plx#1008]
I created a fresh expo app and installed `react-native-ble-plx` according to [these instructions](https://tedbot.com/How-to-Build-a-Bluetooth-App-with-Expo-React-Native-5127b444ac2448baab4948e36ff97088) and if I use the line

```
const manager = new BleManager();
```
The app crashes immediately upon running without any errors or messages of any kind. If I uncomment that line, it works fine.

Any ideas what I can check or do?

**Comment by domenbukovac** [comment]
Are you using Expo Go? If so you need to build custom client since this package requires custom native code. Check out [@config-plugins/react-native-ble-plx](https://www.npmjs.com/package/@config-plugins/react-native-ble-plx)

**Comment by t3db0t** [comment]
@domenbukovac Thanks for your reply! Yes, I am using that package and a custom dev client. I've successfully used it in an app before but this crashing behavior is new and I'm not sure how to debug it.

**Comment by KovD3v** [comment]
Same here

**Comment by KovD3v** [comment]
Solved you have to add this 
<img width="860" alt="Schermata 2022-09-22 alle 19 56 39" src="https://user-images.githubusercontent.com/106698548/191818298-08256488-9130-417f-8e43-a1bff9dd8b02.png">
