### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by bhola-t2b** [dotintent/react-native-ble-plx#1017]
module map file '/Users/t2b/Library/Developer/Xcode/DerivedData/blem2m-ecdewydnbimghkedqzzpibcfvgxw/Build/Intermediates.noindex/ArchiveIntermediates/blem2m/BuildProductsPath/Release-iphoneos/MultiplatformBleAdapter/MultiplatformBleAdapter.modulemap' not found

This i am getting in iOS release

**Comment by KingOfTNT10** [comment]
I dont work with IOS But i think ots becuase you are not running the project but actually the workspace

**Comment by dominik-czupryna-withintent** [comment]
https://github.com/dotintent/react-native-ble-plx/issues/1068
