### ISSUE TITLE
Why doesn't monitor notify for every value change on the characteristic?

### ISSUE THREAD

**Issue by jurck222** [dotintent/react-native-ble-plx#1019]
I am trying to make an app that receives data from a device but when i run the app and send the commands the monitor sometimes outputs the changed value and other times when i run the app it just doesnt do anything.

this is my code for connecting.
![image](https://user-images.githubusercontent.com/56190152/192101462-061d873c-02c5-4fd1-9ee8-a1f0447d192e.png)

and these are functions that i use:
`async function setCaptureActionAUDIO(action, size,device){
    let n = 0;
    let pktsize  = 9;
    let pktdata = new Uint8Array(pktsize);
    for(let i = 0; i<9;i++){
      pktdata[i]= 0x00;
    }
    
    // generate packet
	  pktdata[0] = 0xA5;
	  pktdata[1] = 0x52;
	  pktdata[2] = 0x05;
	  pktdata[3] = action;
    
    n = 4;
    let tmp = size;
    
    pktdata[n+0] = parseInt(tmp/2**24);
	  tmp = tmp - pktdata[n+0]*(2**24)
	  pktdata[n+1] = parseInt(tmp/2**16);
	  tmp = tmp - pktdata[n+1]*(2**16)
	  pktdata[n+2] = parseInt(tmp/2**8);
	  tmp = tmp - pktdata[n+2]*(2**8)
	  pktdata[n+3] = parseInt(tmp);
    txPktBLE(pktdata, pktsize, 0x0012,device);
    console.log("-> BLE: setting action mode"+action+"S \n"+size);
    
  }`

![image](https://user-images.githubusercontent.com/56190152/192101507-8686d42e-9eed-40fd-aaa1-73b58744fecd.png)

`async function readDataAUDIO(device){
    let n = 0;
    let pktsize = 9;
    let pktdata = new Uint8Array(pktsize);
    let bdata = new Uint8Array(2*512*1024);
    let fdata = [];
    let pdata = [];
    for(let i = 0; i<512*1024; i++){
      fdata.push(0);
      pdata.push(0);
    }
    for(let i = 0;i<pktsize;i++){
      pktdata[i] = 0x00;
    }
    pktdata[0] = 0xA5;
    pktdata[1] = 0x53;
    pktdata[2] = 0x00;

    await txPktBLE(pktdata, 4, 0x0012,device);
    
    console.log("-> BLE: waiting for reply...")
    g_ble_rx_rflag=1;
    if(wait4RespBLE(2000) == 0){
      console.log("-> BLE: write timeout")
      return;
    }
    console.log("no timeout");
    
    n = 3;	
    let cap_size = 0;
    let cbyte = (g_ble_rx_pkt[n + 0]);
    cap_size = cap_size + parseInt(cbyte)*(2**24);
    cbyte = (g_ble_rx_pkt[n + 1]);
    cap_size = cap_size + parseInt(cbyte)*(2**16);
    cbyte = (g_ble_rx_pkt[n + 2]);
    cap_size = cap_size + parseInt(cbyte)*(2**8);
    cbyte = (g_ble_rx_pkt[n + 3]);
    cap_size = cap_size + parseInt(cbyte);
    
    console.log("-> BLE: preparing for download of "+cap_size+" B");

    let ridx = 0;
   
      pktdata[0] = 0xA5;
      pktdata[1] = 0x55;
      pktdata[2] = 0x04;
      n = 3;
      let tmp = ridx;
      
      pktdata[n + 0] = parseInt(tmp/2**24)
      tmp = tmp - pktdata[n + 0]*(2**24)
      pktdata[n + 1] = parseInt(tmp/2**16)
      tmp = tmp - pktdata[n + 1]*(2**16)
      pktdata[n + 2] = parseInt(tmp/2**8)
      tmp = tmp - pktdata[n + 2]*(2**8)
      pktdata[n + 3] = parseInt(tmp);
      
      
      await txPktBLE(pktdata, 8, 0x0012,device);
}`

**Comment by AzranAzwer** [comment]
did you find any ?

**Comment by abursztynowska** [comment]
I'm excited to inform you that we've released a new version of `react-native-ble-plx`. Many of the concerns and bugs have been addressed in this update.

If you encounter any issues or have further suggestions, please don't hesitate to open a new issue.
