### ISSUE TITLE
Not able to find the bluetooth connected device list.

### ISSUE THREAD

**Issue by hupptechnologies** [dotintent/react-native-ble-plx#1020]
**Mobile Device Environment**
Provide a list of operating systems on which this issue is relevant.
- Device: iPhone11
- OS: 15

**Application Environment**
Provide information about your development environment:
- React Native version: 0.63.4

**Describe the bug**
When i try to scan or try to find the bluetooth connected device then i am always getting empty array even the bluetooth device is connected.

**Comment by AzranAzwer** [comment]
did you find a solution ?

**Comment by dominik-czupryna-withintent** [comment]
Could you show how you search for devices?
