### ISSUE TITLE
Bug Report 

### ISSUE THREAD

**Issue by MuriloBarranco** [dotintent/react-native-ble-plx#1025]
What is the current behavior?

Please describe the behavior you are expecting
Good night my dears, I am grateful for helping me, I have the following problem, when reading the characteristics of my device, I am receiving two objects, one that returns the value = "000" and the other is correct, but the value = "000" comes last, making me lose the characteristics of my device right

### Steps to Reproduce
My function that returns my characteristics

 const inWeighingUpdate = async (
    error: BleError | null,
    characteristic: Characteristic | null
  ) => {
    const rawData: any = characteristic?.value

    const result = base64.decode(rawData)
    setHeartRate(result)

    if (error) {
      console.log(error)
    }
  }

Thanks in advance for your attention! <3

**Comment by dominik-czupryna-withintent** [comment]
The new major release updates the core packages that support the latest versions of the operating system and fixes some old bugs. Please confirm if the issue still persists and create a new issue if it still does.
