### ISSUE TITLE
I can connect but cannot write on the device

### ISSUE THREAD

**Issue by AzranAzwer** [dotintent/react-native-ble-plx#1029]
## after I connect to the device i'm getting the response. But after that when try to send data, iis giving me the attached error.

my code is below.

        const conectedDevice = await manager.connectToDevice(device.id)

        await device.discoverAllServicesAndCharacteristics()

        const services = await device.services()

        const characteristics = await services[1].characteristics()

        const characteristic = _.find(
          characteristics,
          ({isWritableWithResponse}) => isWritableWithResponse === true,
        )

       const base64Data = base64.encode(
          '{ "Command": "SALE", "Amount": "000000001000" }',
        )

        const response = await characteristic.writeWithResponse(base64Data)

        // const response =await device.writeCharacteristicWithResponseForService(
        //   '"4DF91029-B356-463E-9F48-BAB077BF3EF5"',
        //   characteristic.uuid,
        //   base64Data,
        // )

        // const response = await manager.writeCharacteristicWithResponseForDevice(
        //   characteristic.deviceID,
        //   characteristic.serviceUUID,
        //   characteristic.uuid,
        //   base64Data,
        // )
        console.log('response', response)

<img width="1282" alt="Screen Shot 2022-11-02 at 12 04 59 PM" src="https://user-images.githubusercontent.com/28869406/199433469-6b735b4d-fbff-4d5f-8b3e-abf05bb5da7f.png">

**Comment by ziedhajsalah** [comment]
@AzranAzwer , did you manage to fix this issue?

**Comment by AzranAzwer** [comment]
no

**Comment by AzranAzwer** [comment]
Hi All I have fixed this issue

Actually my encryption was wrong after I tried for couple of methods, I got the exact encryption way.

**Comment by hoanghai9650** [comment]
can you share how did you encrypt ?
