### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by KumailAhmedWellwink** [dotintent/react-native-ble-plx#1032]
## Current Behavior

the package working fine in Android 11

## New behavior

the package not working in Android 12

**Comment by dominik-czupryna-withintent** [comment]
Check Android permissions:
Check if you requested following permissions
PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION eg.
```
const locationAccessGranted = await PermissionsAndroid.request(
       PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
       );
```
PermissionsAndroid.PERMISSIONS.BLUETOOTH_SCAN
PermissionsAndroid.PERMISSIONS.BLUETOOTH_CONNECT

Check if your AndroidManifest.xml (android/app/src/main/AndroidManifest.xml) includes Android 12+ (SDK 31) and Android up to 11 (SDK 30) permissions:
```
    <!-- Android >= 12 -->
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <!-- Android < 12 -->
    <uses-permission android:name="android.permission.BLUETOOTH" android:maxSdkVersion="30" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" android:maxSdkVersion="30" />
    <!-- common -->
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
```
