### ISSUE TITLE
Question: Can we use this package to connect with ELM327 OBD 2 devices?

### ISSUE THREAD

**Issue by mehthabt** [dotintent/react-native-ble-plx#1036]
Can we use this package to connect with ELM327 OBD 2 devices? 
if yes , can anyone show me an example how i can i connect and read the data with AT commands 
Thanks in advance

**Comment by dominik-czupryna-withintent** [comment]
Yes, as far as I know, ELM327 devices use BLE, but when it comes to handling communication between such a device and a car, you should look for it in the CAN bus documentation.
