### ISSUE TITLE
Can't find Device HC-05

### ISSUE THREAD

**Issue by koen1711** [dotintent/react-native-ble-plx#1044]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm sure that question is related to the library itself and not Bluetooth Low Energy or Classic in general. If that so, please post your question on [StackOverflow](https://stackoverflow.com/questions/tagged/react-native-ble-plx?sort=active) or on our [Gitter](https://gitter.im/RxBLELibraries/react-native-ble) channel.

## Question

So, I am trying to find my Bluetooth device (HC-05: https://www.tinytronics.nl/shop/nl/communicatie-en-signalen/draadloos/bluetooth/modules/bluetooth-hc-05-module-rf-transceiver-master-en-slave) but it can't find it, it does find other bluetooth devices and I am sure it is on and stuff.

**Comment by dariuszseweryn** [comment]
HC-05 is a Bluetooth Classic device, not a BLE device
