### ISSUE TITLE
After Receiving characteristcs and services the device show BLE Error (Device  xxxxxxxxxxx is not connected)  in IOS

### ISSUE THREAD

**Issue by KumailAhmedWellwink** [dotintent/react-native-ble-plx#1045]
## Prerequisites
After Receiving characteristcs and services the device show BLE Error (Device  xxxxxxxxxxx is not connected) 
when calling ( blemanager.readCharacteristics ,bleManager.monitorCharacteristicForDevice.) it shows BLE ERROR: Device is not connected is IOS Device

**Comment by Killyannoor** [comment]
Have you been able to resolve this yet? Also, what version of React Native are you using? I am experiencing the same problem on 0.70.6

**Comment by dominik-czupryna-withintent** [comment]
I can't recreate this bug. Could you attach a code snippet that shows how you connect to the device and how you read the characteristics?
