### ISSUE TITLE
Error BLUETOOTH_CONNECT (android permission)

### ISSUE THREAD

**Issue by VirtuozTM** [dotintent/react-native-ble-plx#1049]
Hello everyone,

I'm contacting you about a problem I can't seem to solve (about, in my opinion, android permissions). 

The problem is the following: I have a mobile application developed in React Native in TypeScript language. Let's take the case, where the problem occurs. I am on a screen and I click on a button. This button makes me navigate to another screen and when I open this screen, I ask for different permissions (such as location, bluetooth etc). I did all my tests on my phone which has an android version 10. Everything works perfectly! However, as soon as I use a friend's phone which has an android 12 version, I get an error when I navigate to the screen. The navigation is fine but when asking for permissions either :
- the application crashes
- the requests are done but the application is totally buggy and I have to restart it.
 
In conclusion, when the application is initialized, from the first installation, the permission requests break the application.

I asked help Dan (from https://www.youtube.com/@DanRNLab) because he did a lot of video on BLE. He recommended that I follow his video to fix the android 12 problems but I had already done that :( and it didn't solve my problem.

So you are my last chance to find the error.

A video showing the process and photos are attached.  

Hoping that you can help me.

![erreur_bluetooth_connect](https://user-images.githubusercontent.com/105630116/213995583-5f3215f8-1f8c-420b-80c7-0357db6e7e81.jpg)

https://user-images.githubusercontent.com/105630116/213995590-ea5d2b90-7478-443b-8f1d-6d6d57e9e445.mp4

![code_permissions1](https://user-images.githubusercontent.com/105630116/213995613-ab1a13cb-585f-427d-8cc3-bc55fc29b77b.jpg)
![code_permissions2](https://user-images.githubusercontent.com/105630116/213995615-c331d638-3b3a-4c4e-a076-71be7d13d9b2.jpg)

**Comment by will-thrive** [comment]
Hi VirtuozTM.  I have BLE working on Android 13 (and 12 too I believe.). I have checked my android/app/src/main/AndroidManifest.xml file and my BLE code.  The only real difference I can see to yours is that I do NOT have or use BLUETOOTH_ADVERTISE in either.  Are you sure you need this?  I mean, do you need to send advertisements?  Usually advertisments come from the device, i.e. from the server.

**Comment by VirtuozTM** [comment]
I remove BLUETOOTH_ADVERTISE but it doesn't change anything :(. I have the impression that BLUETOOTH_CONNECT is ghosted. I have those versions : 
 "react-native-base64": "^0.2.1",
 "react-native-ble-manager": "^8.4.1",
 "react-native-ble-plx": "^2.0.3",
 "react-native-bluetooth-state-manager": "^1.3.3"

**Comment by VirtuozTM** [comment]
Btw, when I'm going in the settings of my application on the phone. "Authorizations" are disabled and I can active them manually (as you can see on the screenshot just under)
![disabled_actived](https://user-images.githubusercontent.com/105630116/214003993-3ec637f5-c7e1-437d-bb8f-7c7377a6420b.jpeg)

**Comment by will-thrive** [comment]
You have both "react-native-ble-manager": "^8.4.1" and "react-native-ble-plx": "^2.0.3".  I use only "react-native-ble-plx": "^2.0.3".  You only need one BLE liberary or the other, not both.  Are you actually using react-native-ble-manager?

**Comment by VirtuozTM** [comment]
I use only "react-native-ble-plx" as well. I tried "react-native-ble-manager" ealier to compare both librairies. Globally I use : "react-native-base64": "^0.2.1",
"react-native-ble-plx": "^2.0.3",
"react-native-bluetooth-state-manager": "^1.3.3",
"react-native-permissions": "^3.6.1",

I update my version of react-native-permissions from 3.3.1 to 3.6.1 but it doesn't change anything

**Comment by VirtuozTM** [comment]
I can add other informations. When I navigate to the screen I use in a 
` useEffect(() => {
    initBleScanner(serviceUUID);
  }, [initBleScanner, serviceUUID]);`

I call an function which name is `initBleScanner`. It looks like : 

`const initBleScanner = useCallback(
    (UUID_DEVICE: string) => {
      requestPermissions((permissionsGranted: boolean) => {
        if (permissionsGranted) {
          // Code pour continuer avec le scan
          const subscription = manager.current.onStateChange(state => {
            if (state === 'PoweredOn') {
              scanDevices(UUID_DEVICE);
              subscription.remove();
            }
          }, true);
        } else {
          // Code pour gérer l'absence de permission
        }
      });
    },
    [scanDevices],
  );
`

Finally, the `requestPermissions((permissionsGranted: boolean)` is : 

`const requestPermissions = async (callback: PermissionCallBack) => {
    if (Platform.OS === 'android') {
      const apiLevel = await DeviceInfo.getApiLevel();
      if (apiLevel < 31) {
        const grantedStatus = await PermissionsAndroid.request(
          PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
        );
        callback(grantedStatus === PermissionsAndroid.RESULTS.GRANTED);
      } else {
        const result = await requestMultiple([
          PERMISSIONS.ANDROID.BLUETOOTH_SCAN,
          PERMISSIONS.ANDROID.BLUETOOTH_CONNECT,
          PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION,
        ]);
        const isAllPermissionsGranted =
          result['android.permission.BLUETOOTH_SCAN'] ===
            PermissionsAndroid.RESULTS.GRANTED &&
          result['android.permission.BLUETOOTH_CONNECT'] ===
            PermissionsAndroid.RESULTS.GRANTED &&
          result['android.permission.ACCESS_FINE_LOCATION'] ===
            PermissionsAndroid.RESULTS.GRANTED;
        callback(isAllPermissionsGranted);
      }
    } else {
      callback(true);
    }
  };
`

**Comment by VirtuozTM** [comment]
Hi @redko-o,

I finnaly found the issue and solved it. I was trying to ask the user to activate Bluetooth before I asked and got the BLUETOOTH_CONNECT permission.

So the solution is : 
```
const result = await requestMultiple([
            PERMISSIONS.ANDROID.BLUETOOTH_CONNECT,
            PERMISSIONS.ANDROID.BLUETOOTH_SCAN,
            PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION,
          ]);
          if (
            result['android.permission.BLUETOOTH_CONNECT'] ===
            PermissionsAndroid.RESULTS.GRANTED
          ) {
            enableBluetooth();
```
wtih : 
`const enableBluetooth = async () => {
    const isBluetoothEnabled = await BluetoothStateManager.requestToEnable();
    if (!isBluetoothEnabled) {
      await BluetoothStateManager.enable();
    }
  };`

Btw, I use react-native-ble-plx and react-native-bluetooth-state-manager

I hope it will help you as much as possible

**Comment by dominik-czupryna-withintent** [comment]
In Android 12+ the full BT management feature has been removed. Currently, it is no longer possible to turn BT on or off from the app. You can ask the user to turn it on, but this requires the BLUETOOTH_SCAN permission. The library supports this change since version 3.0.0.
