### ISSUE TITLE
Is this library compatible with React-Native "New Architecture"?

### ISSUE THREAD

**Issue by ablack34** [dotintent/react-native-ble-plx#1050]
I may have to migrate a project to the latest version of React-Native with the "New Architecture". Is this library compatible with the New Architecture or is it planning on becoming compatible? 

Thanks!

**Comment by fgrs** [comment]
I don't think this library works with RN 0.71.2 I get this error "cannot start scanning operation" and "could not find callback wrapper"

**Comment by lucaswitch** [comment]
I guess it not supports since the last release was on 2021.

**Comment by lucaswitch** [comment]
But it works on 0.71 apps completely fine.

**Comment by ablack34** [comment]
Ok thanks, I'm assuming that means the maintainers aren't active? If that's the case is there a recommended maintained RN Bluetooth Library?

**Comment by ScreamZ** [comment]
https://github.com/innoveit/react-native-ble-manager

**Comment by bj97301** [comment]
> https://github.com/innoveit/react-native-ble-manager

Seems like it may require ejecting from expo.

**Comment by gabimoncha** [comment]
@ablack34 it seems to be #1089
