### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fullstact69** [dotintent/react-native-ble-plx#1053]
Hi, Different Errors are occurred when the ble is tried to scan.

PermissionsAndroid.check(PermissionsAndroid.PERMISSIONS.ACCESS_COARSE_LOCATION) 
this is returned True. But, below error is made when startDeviceScan,  
BleError: Location services are disabled. 

How to resolve it? Thank you.

**Comment by allencit** [comment]
I encountered the same issue and found that my phone had turned off location services at the system global level. Turning it back on may solved the issue.
