### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by fullstact69** [dotintent/react-native-ble-plx#1054]
[bleManager.startDeviceScan not working on iOS react-native-ble-plx](https://stackoverflow.com/questions/67884535/blemanager-startdevicescan-not-working-on-ios-react-native-ble-plx)

**Comment by dominik-czupryna-withintent** [comment]
The new major release updates the core packages that support the latest versions of the operating system and fixes some old bugs. Please confirm if the issue still persists and create a new issue if it still does.
