### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by gabefgonc** [dotintent/react-native-ble-plx#1058]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior

Expected to open my app and run it without any issues

## Current Behavior

When starting the app I get the error:

### Steps to Reproduce

clone the repo
install with npm

npx expo start

### Context

Using Expo ~48.0.3

* Library version: 2.0.3
* Platform: Android
* JS logs:
* Formatted code sample or link to a repository: [github repo](https://github.com/gabefgonc/rgbled-controller)

**Comment by dominik-czupryna-withintent** [comment]
Full compatibility with expo has not been implemented yet check https://www.npmjs.com/package/@config-plugins/react-native-ble-plx
