### ISSUE TITLE
Metro Error

### ISSUE THREAD

**Issue by hypext1** [dotintent/react-native-ble-plx#1061]
## Expected Behavior

Library behaves exactly the same on iOS regardless of building with Metro or without building for TestFlight.

## Current Behavior

Library scans for devices on network and finds the device I told it to find when built using Metro, but can't find the device on the network when built for release on TestFlight.

### Steps to Reproduce

Make an app for finding devices on network
Build using Metro
Build for "Release"

### Context

React Native 0.69.1
xcode 14.2
latest version of react-native-ble-plx

**Comment by dominik-czupryna-withintent** [comment]
The latest version (3.0.0) of the library has been tested in the release version and no error was found. Please confirm if the issue still persists and create a new issue if it still does.
