### ISSUE TITLE
Bug Report - Differing number of services between iOS and Android

### ISSUE THREAD

**Issue by nmurashi** [dotintent/react-native-ble-plx#1062]
## Expected Behavior

After a device.discoverAllServicesAndCharacteristics() call, I expect to see the same number of services for both Android and iOS.

## Current Behavior

I see a different number of services. In my instance, I see 5 services on Android and 3 on iOS.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

0. Open on Android or iOS
1, Scan for devices
2. Connect to device
3. Do device.discoverAllServicesAndCharacteristics() to the connected device
4. Check the length of services found
5. Repeat for other platform

### Context

The BLE device in question is a CodeLess 14531.

On Android I see:
```
Array [
  "00001800-0000-1000-8000-00805f9b34fb",
  "00001801-0000-1000-8000-00805f9b34fb",
  "0000fef5-0000-1000-8000-00805f9b34fb",
  "866d3b04-e674-40dc-9c05-b7f91bec6e83",
  "0783b03e-8535-b5a0-7140-a304d2495cb7",
]
```

On iOS I see:
```
Array [
  "0000fef5-0000-1000-8000-00805f9b34fb",
  "866d3b04-e674-40dc-9c05-b7f91bec6e83",
  "0783b03e-8535-b5a0-7140-a304d2495cb7",
]
```

The difference being the missing 00001800/1801 UUIDs. 

Admittedly I'm a novice with BLE, so perhaps they're generic services that iOS just filters for whatever reason. If that's the case, I apologize for the errant bug report! But I didn't see anything in the documentation mentioning this nor did a Google search turn up much. Though I found that 00001800 appears to be a commonly used UUID, which makes me think iOS _wouldn't?_ filter it. 

The relevant code to replicate this (besides the scanning/connecting part) is below.

```js
await device.discoverAllServicesAndCharacteristics();
const services = await device.services();
const uuid_services = services.map(function(obj) {
    return obj.uuid;
})
console.log(uuid_services);
```

**Comment by dominik-czupryna-withintent** [comment]
1800 and 1801 are generic system services and as far as I know, iOS does not show the GAP service to the developer
