### ISSUE TITLE
When will there be a new release?

### ISSUE THREAD

**Issue by AleksandarKeeprop** [dotintent/react-native-ble-plx#1063]
I was wondering when will the new release of this library be available? Is this something anyone has some kind of information about?

The issue I'm having has been fixed on the 22nd of August 2022 for OneKeyHQ/hardware-js-sdk (https://github.com/OneKeyHQ/hardware-js-sdk/pull/119).

**Comment by pawlo1337** [comment]
Dear Friend, thank you for your patience. We will proceed crucial development works within next 2 months and the library will stay maintained. 

> I was wondering when will the new release of this library be available? Is this something anyone has some kind of information about?
> 
> The issue I'm having has been fixed on the 22nd of August 2022 for OneKeyHQ/hardware-js-sdk ([OneKeyHQ/hardware-js-sdk#119](https://github.com/OneKeyHQ/hardware-js-sdk/pull/119)).
