### ISSUE TITLE
Send Data and Retrieve response from bluetooth device

### ISSUE THREAD

**Issue by laurenkumar** [dotintent/react-native-ble-plx#1065]
## Question

Hello, I'm trying to receive data from a smartwatch (HK85).
The connection and writing is working great. 
But nor notify nor read is working.
And I guess that's normal since isNotifiable is set to false and read as well.

`"_activePromises": {}, 
"_activeSubscriptions": {},
"deviceID":"8E:75:D1:20:6A:2B",
"id":4,
"isIndicatable":false,
"isNotifiable":false,
"isNotifying":false,
"isReadable":false,
"isWritableWithResponse":true,
"isWritableWithoutResponse":true,
"serviceID":3,
"serviceUUID":"6e400001-b5a3-f393-e0a9-e50e24dcca9e",
"uuid":"6e400002-b5a3-f393-e0a9-e50e24dcca9e"`

What I don't understand is the fact that I have a SDK for Android (that comes with the watch) and basically when they want access to say the battery of the device, it writes data to it and then receives a package:

_BleConnector sendData -> 0x0203_POWER, 0x10_READ
V/BaseBle: BleMessenger enqueueMessage -> WriteMessage(service='6e400001-b5a3-f393-e0a9-e50e24dcca9e', characteristic='6e400002-b5a3-f393-e0a9-e50e24dcca9e', data=0xAB, 0x01, 0x00, 0x03, 0xFC, 0xA0, 0x02, 0x03, 0x10
V/BaseBle: MessageTask -> try(1), WriteMessage(service='6e400001-b5a3-f393-e0a9-e50e24dcca9e', characteristic='6e400002-b5a3-f393-e0a9-e50e24dcca9e', data=0xAB, 0x01, 0x00, 0x03, 0xFC, 0xA0, 0x02, 0x03, 0x10
V/BaseBle: BleMessenger enqueueWritePackets -> WriteMessage(service='6e400001-b5a3-f393-e0a9-e50e24dcca9e', characteristic='6e400002-b5a3-f393-e0a9-e50e24dcca9e', data=0xAB, 0x01, 0x00, 0x03, 0xFC, 0xA0, 0x02, 0x03, 0x10
I/BaseBle: AbsBleConnector **onCharacteristicWrite** -> 0 SUCCESS, 6e400002-b5a3-f393-e0a9-e50e24dcca9e, 0xAB, 0x01, 0x00, 0x03, 0xFC, 0xA0, 0x02, 0x03, 0x10
V/BaseBle: BleMessenger dequeueWritePacket
I/BaseBle: AbsBleConnector **onCharacteristicChanged** -> 6e400003-b5a3-f393-e0a9-e50e24dcca9e, 0xAB, 0x11, 0x00, 0x04, 0x87, 0xFD, 0x02, 0x03, 0x10, 0x54
V/BaseBle: BleParser -> data length=10, received=10_

So I'm a bit stuck at understanding how this works and I guess some answer reside in the onCharacteristicChanged, but how does that translate with this library ?

Thank you for your time

**Comment by dominik-czupryna-withintent** [comment]
I am afraid that the device may have custom services or the problem is in the declaration itself. Before setup indication or setup notification, our package first checks the isIndicatable and isNotifiable flags and if both are declared as false, it does not even attempt to connect. So the description would suggest that it is actually notifiable, but the manufacturer declares something different.
