### ISSUE TITLE
DiscoverAllServicesAndCharacteristicsForDevice operation timeout error

### ISSUE THREAD

**Issue by ablack34** [dotintent/react-native-ble-plx#1066]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [x] I'm sure that question is related to the library itself and not Bluetooth Low Energy or Classic in general. If that so, please post your question on [StackOverflow](https://stackoverflow.com/questions/tagged/react-native-ble-plx?sort=active) or on our [Gitter](https://gitter.im/RxBLELibraries/react-native-ble) channel.

## Question

Hello,

I am trying to discover all services and characteristics for my connected device but I keep getting an error.

connectToDevice: {"message":"Operation timed out","errorCode":3,"attErrorCode":null,"iosErrorCode":null,"androidErrorCode":null,"reason":"GATT exception from MAC address 76:05:9F:C6:86:91, with type BleGattOperation{description='SERVICE_DISCOVERY'}","name":"BleError"}

The operation is timing out, I have tried extending the default time but I still get the same error. Any ideas as to why this doesn't discover services and characteristics first time?

`const connectToDevice = async (deviceId:DeviceId) => {

                
            try{
                //stop scanning for devices
                bleManager.stopDeviceScan();

            
                //use BleManager to connect to device
                const deviceConnection = await bleManager.connectToDevice(deviceId);
                console.log('Connected To Device: ' + deviceId);

                //monitor disconnections
                deviceConnection.onDisconnected((error, disconnectedDevice) => {
                    console.log('onDisconnected Device disconnected: ' + disconnectedDevice.id);
                    //events.emit("connectionError", true)
                    
                });

                if(await bleManager.isDeviceConnected(deviceId)){
                    //console.log('before ServiceDiscovery ' + deviceId + ' is connected ' + await bleManager.isDeviceConnected(deviceId));

                    console.log('discoverAllServicesAndCharacteristicsForDevice called');
                    //console.log('before ServiceDiscovery ' + deviceId + ' is connected ' + await bleManager.isDeviceConnected(deviceId));
                            
                    await bleManager.discoverAllServicesAndCharacteristicsForDevice(deviceId);
                            
                    //events.emit("connectionError", true)
                    console.log('Read Validation Char called');
                    readValidationChar(deviceId);
                }
                    
            }
            catch(error){
                console.log("connectToDevice: " + JSON.stringify(error));
                throw new Error("Failed to connect to device");
                
            }

        }`

**Comment by dominik-czupryna-withintent** [comment]
The new major release updates the core packages that support the latest versions of the operating system and fixes some old bugs. Please confirm if the issue still persists and create a new issue if it still does.
