### ISSUE TITLE
Getting "Scan failed because feature unsupported (code 8)" when calling startDeviceScan() for Android devices

### ISSUE THREAD

**Issue by jaewondong** [dotintent/react-native-ble-plx#1073]
## Expected Behavior

Scan BLE peripherals with startDeviceScan()

## Current Behavior

Runs for IOS, but returns "Scan failed because feature unsupported (code 8)" for Android.
Error message:
```
{"message":"Cannot start scanning operation","errorCode":600,"attErrorCode":null,"iosErrorCode":null,"androidErrorCode":null,"reason":"Scan failed because feature unsupported (code 8)","name":"BleError"}
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. ...

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Both JS and platform logs can be enabled via [setLogLevel](https://dotintent.github.io/react-native-ble-plx/#blemanagersetloglevel) function call. 

- react: 17.0.2
- react-native: 0.67.3
- react-native-ble-plx: 2.0.3
- Platform: Android/iOS.
- Android Device: Pixel 2, Android 12 (API 31)

```ts
bleManager.startDeviceScan(null, 
      {
        scanMode: ScanMode.LowLatency,
        callbackType: ScanCallbackType.FirstMatch,
      },
      async (error, device) => {
        if (error) {
          this.bleManager.stopDeviceScan();
          console.error('error scanning');
          console.log(JSON.stringify(error));
          rejectDevicePromise(error);
          return;
        }
        if (device?.localName === this.peripLocalName) { ... }
```

**Comment by thuantvDr4** [comment]
same issue, what's any solution? please

**Comment by dominik-czupryna-withintent** [comment]
This is the error on the android side: https://developer.android.com/reference/android/bluetooth/le/ScanCallback#SCAN_FAILED_FEATURE_UNSUPPORTED
Most likely, the device has a problem with ScanMode.LowLatency. I tried to reproduce this problem on a phone with the same SoC but I didn’t find any problems. Could you confirm the issue after updating the package?
