### ISSUE TITLE
How do I set up logging and use for react-native-ble-plx in VSCode? 

### ISSUE THREAD

**Issue by ablack34** [dotintent/react-native-ble-plx#1075]
Hello,

I am currently building an application that connects to Bluetooth signal emitter, the signals are listened for in the app and then depending on the value perform a certain action.

I want to set up logging so I can see in detail what exactly the state of the BLE interactions are as it can be a bit temperamental.

I have added the below code but don't know how output the logs or where to actually see the logs VSCode.

`const bleManager = new BleManager();
bleManager.setLogLevel(LogLevel.Verbose);`

For example, one of the methods I want to debug and see logs for is:

`const connectToDevice = async (deviceId: DeviceId): Promise<Device | null> => {
    try {
      bleManager.stopDeviceScan();

      const deviceConnection = await bleManager.connectToDevice(deviceId);
      console.log('Connected To Device: ' + deviceId);

      deviceConnection.onDisconnected((error: BleError|null, disconnectedDevice:Device) => {
        console.log("onDisconnected BleError: " + JSON.stringify(error));
        handleDisconnection(JSON.stringify(error), disconnectedDevice.id );
      });

      console.log('discoverAllServicesAndCharacteristicsForDevice called');
      const device = await bleManager.discoverAllServicesAndCharacteristicsForDevice(deviceId);
      console.log(JSON.stringify(device));
      console.log('discoverAllServicesAndCharacteristicsForDevice success!');

      return deviceConnection;
    } catch (error) {
      console.log('discoverAllServicesAndCharacteristicsForDevice Failed!');
      handleConnectionFailed(
        new Error(
          'discoverAllServicesAndCharacteristicsForDevice Failed! - ' + error,
        ),
      );
      //bleManager.cancelDeviceConnection(deviceId);
      return null;
    }
  };`

**Comment by dominik-czupryna-withintent** [comment]
Following documentation: setLogLevel(logLevel) - Sets new log level for native module's logging mechanism. - logLevel mechanism works on the native side (under the hood there are two packages for Android and for iOS) this function forwards logLevel into those packages and it’s so the logs stay on the native side. You can check them in xCode for iOS or in Logcat for Android.
