### ISSUE TITLE
[Android] BleError: Device ? is not connected

### ISSUE THREAD

**Issue by devcocup** [dotintent/react-native-ble-plx#1076]
I am getting the crash report from bugsnag for Android platform only. I am not sure when this error comes.

LOG:

> BleError · Device ? is not connected
> (native) construct
> node_modules/@babel/runtime/helpers/wrapNativeSuper.js:17:13 Wrapper
> (native) construct
> index.android.bundle:1:1295746 _createSuperInternal
> (native) call
> node_modules/react-native-ble-plx/src/BleError.js:47:4 BleError
> node_modules/react-native-ble-plx/src/BleError.js:75:27 parseBleError
> node_modules/react-native-ble-plx/src/BleManager.js:174:25 ?anon_0_
> (native) throw
> node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:23 asyncGeneratorStep
> node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:26 _throw
> /root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/164673tg/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16 tryCallOne
> /root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/164673tg/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27 anonymous
> (native) apply
> node_modules/react-native/Libraries/Core/Timers/JSTimers.js:248:22 anonymous
> node_modules/react-native/Libraries/Core/Timers/JSTimers.js:112:14 _callTimer
> node_modules/react-native/Libraries/Core/Timers/JSTimers.js:162:14 _callReactNativeMicrotasksPass
> node_modules/react-native/Libraries/Core/Timers/JSTimers.js:413:41 callReactNativeMicrotasks
> node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:390:41 __callReactNativeMicrotasks
> node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:132:38 anonymous
> node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:367:10 __guard
> node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:131:16 flushedQueue
> node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:127:28 invokeCallbackAndReturnFlushedQueue

version: 2.0.3

**Comment by dominik-czupryna-withintent** [comment]
The new major release updates the core packages that support the latest versions of the operating system and fixes some old bugs. Please confirm if the issue still persists and create a new issue if it still does.
