### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by GokulKir** [dotintent/react-native-ble-plx#1081]
Scan error: [BleError: Device is not authorized to use BluetoothLE]

**Comment by dominik-czupryna-withintent** [comment]
Check Android permissions:
Check if you requested following permissions
PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION eg.
```
const locationAccessGranted = await PermissionsAndroid.request(
       PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
       );
```
PermissionsAndroid.PERMISSIONS.BLUETOOTH_SCAN
PermissionsAndroid.PERMISSIONS.BLUETOOTH_CONNECT

Check if your AndroidManifest.xml (android/app/src/main/AndroidManifest.xml) includes Android 12+ (SDK 31) and Android up to 11 (SDK 30) permissions:
    
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    
    <uses-permission android:name="android.permission.BLUETOOTH" android:maxSdkVersion="30" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" android:maxSdkVersion="30" />
    
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
