### ISSUE TITLE
discoverAllServicesAndCharacteristics() hangs and disconnects on IOS but not android

### ISSUE THREAD

**Issue by WallPulse-Decor** [dotintent/react-native-ble-plx#1082]
Hi all, I'm working to implement ble support in my app but I'm running into a strange issue where I connect to the device on IOS but then when I try to run discoverAllServicesAndCharacteristics() with await it just hangs and then disconnects with no further error on IOS. The connection works like a dream on Android so I dont know why this is not working. 

Very rarely the services will be discovered as intended but I have no clue what influences a successful run versus the problematic ones.

Has anyone experienced anything like this and if so could tell me what I'm doing wrong?

I feel like I'm doing something wrong versus there being something wrong with the library itself.

Other info: 
Iphone 12 
IOS: 16.6 
Using Expo

`

  const connectToDevice = async (device) => {
    console.log(device);
    try{
      bleManager.stopDeviceScan();
     
      
      const deviceConnection = await bleManager.connectToDevice(device.id);
      setConnectedDevice(deviceConnection);
      console.log("DEVICE CONNECTED");
     
       
      await deviceConnection.discoverAllServicesAndCharacteristics()
  
     

     
      setConnectedSerivce(targetService)

      if(!targetService){
        console.log("TARGET SERVICE NOT FOUND")
        return 
      } 

      const characteristics = await device.characteristicsForService(targetService.uuid);

      const writableCharacteristic = characteristics.find(characteristic => characteristic.isWritableWithResponse);
      console.log("Characteristic FOUND");
      if (!writableCharacteristic) {
        console.log("WRITABLE CHARACTERISTIC NOT FOUND")
        return 
      }

      setConnectedCharacteristic(writableCharacteristic)

      device.monitorCharacteristicForService(targetService.uuid, writableCharacteristic.uuid, (error, characteristic) => {
        if (error) {
          console.log("ERROR MONITORING:", error);
      
        } else if (characteristic) {
          console.log("MONITORING");
          // The value is base64 encoded, so we need to decode it
          const value = base64.decode(characteristic.value);

          setResponseMessage(value)

          
        }
      });
    
  }
  catch(error){
    console.log("GENERAL ERROR CONNECTING:", error);
   
  }
}

`

**Comment by dominik-czupryna-withintent** [comment]
The new major release updates the core packages that support the latest versions of the operating system and fixes some old bugs. Please confirm if the issue still persists.
