### ISSUE TITLE
isNotifiable cannot receive data

### ISSUE THREAD

**Issue by shinnachot** [dotintent/react-native-ble-plx#1088]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ yes] I am running the latest version
- [ yes] I checked the documentation and found no answer
- [ yes] I checked to make sure that this issue has not already been filed
- [yes ] I'm sure that question is related to the library itself and not Bluetooth Low Energy or Classic in general. If that so, please post your question on [StackOverflow](https://stackoverflow.com/questions/tagged/react-native-ble-plx?sort=active) or on our [Gitter](https://gitter.im/RxBLELibraries/react-native-ble) channel.

## Question

Please describe the question.

My device using oximeter, thermometer, blood pressure and i want to get notification from device when devices have a new data

Here is my characteristic value
```
deviceID : "C0:26:DA:04:75:48"
id: 38
isIndicatable: false
isNotifiable: true
isNotifying: false
isReadable: false
isWritableWithResponse: true
isWritableWithoutResponse: false
serviceID: 37
serviceUUID: "00001523-1212-efde-1523-785feabcd123"
uuid: "00001524-1212-efde-1523-785feabcd123"
value: null
```

and here is my code for start notification
```
characteristics.forEach(async (cha) => {
    console.log('CHA', cha);
    var deviceID = cha.deviceID;
    var serviceUUID = cha.serviceUUID;
    var uuid = cha.uuid;

    if(cha.isNotifiable === true){
      console.log("characteristic foreach start")
      console.log(cha);
      cha.monitor((err, update) => {
          if (err) {
              console.log(`characteristic error: ${err}`);
              console.log(JSON.stringify(err));
          } else {
              var data = parseInt(base64.decode(update.value));
              console.log(data);
          }
      });
  }
```

and i also try 
`monitorCharacteristicForService`
`monitorCharacteristicForDevice`
still not get notification from device what should i do please help

**Comment by dominik-czupryna-withintent** [comment]
I tested your code
```js
  const monitorForAllAvailableCharacteristics = () => {
    BLEService.getCharacteristicsForDevice(deviceTimeService).then(characteristics => {
      if (!characteristics) {
        throw new Error('characteristics error')
      }

      characteristics.forEach(async cha => {
        if (cha.isNotifiable === true) {
          console.log(`started monitor for: ${cha.uuid}`)
          cha.monitor((err, update) => {
            if (err) {
              console.log(`characteristic error: ${err}`)
              console.log(JSON.stringify(err))
            } else {
              console.log(`received message: ${base64.decode(update?.value)}`)
            }
          })
        }
      })
    })
  }
```
output:
```
 LOG  started monitor for: 00002a2b-0000-1000-8000-00805f9b34fb
 LOG  received message: This code works
```
and it works fine.

Can you tell me what steps you take before your function?
