### ISSUE TITLE
Question : Android minSdkVersion

### ISSUE THREAD

**Issue by rvasseur31** [dotintent/react-native-ble-plx#1101]
### Prerequisites

- [X] I checked the documentation and FAQ without finding a solution
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm sure that question is related to the library itself and not Bluetooth Low Energy or Classic in general. If that so, please post your question on [StackOverflow](https://stackoverflow.com/questions/tagged/react-native-ble-plx?sort=active).
- [X] I'm running the latest version

### Question

What causes the minSdkVersion on Android to be set to 23?

**Comment by dominik-czupryna-withintent** [comment]
@gmiszewski-intent

**Comment by bj97301** [comment]
Need to update your expo client to 49.  This fixed it for me on v3 of this package.

**Comment by bj97301** [comment]
I upped my expo to 49 but still see this error as well on Android:
![Screenshot 2023-09-29 at 11 50 16 AM](https://github.com/dotintent/react-native-ble-plx/assets/1450431/cce4a65e-0cb9-4ca5-8f51-14f75c4833e5)

**Comment by eddyv19** [comment]
You need to use expo-build-properties and set the minSdkVersion in your app.json file. This will make the problem go away.  I had the same issue.

**Comment by bj97301** [comment]
> You need to use expo-build-properties and set the minSdkVersion in your app.json file. This will make the problem go away. I had the same issue.

Gonna try this soon. Thank you very much ❤️❤️❤️

**Comment by bj97301** [comment]
This seems to have done the trick.  Thank you @eddyv19.  

```bash
npx expo install expo-build-properties
```

```js
   plugins: [
      [
        'expo-build-properties',
        {
          android: {
            minSdkVersion: 23,
          },
        },
      ],
```

**Comment by bj97301** [comment]
@dominik-czupryna-withintent want me to update the expo installation docs to include this?

**Comment by dominik-czupryna-withintent** [comment]
@bj97301  We are currently checking the lib compatibility with downgraded minSDK to version 21, so it is possible that we will solve this problem in a different way (version 21 is currently the default version for the react-native template).

**Comment by bj97301** [comment]
> @bj97301 We are currently checking the lib compatibility with downgraded minSDK to version 21, so it is possible that we will solve this problem in a different way (version 21 is currently the default version for the react-native template).

Got it.  Welp, let me know if I can help.  I love this package and what you guys are doing.

**Comment by dominik-czupryna-withintent** [comment]
minSdkVersion has been lowered to 21
