### ISSUE TITLE
🐛 onDisconnected callback is never triggering 

### ISSUE THREAD

**Issue by simonitfi** [dotintent/react-native-ble-plx#1126]
### Expected Behavior

//monitor disconnections
deviceConnection.onDisconnected((error, disconnectedDevice) => {
    console.log('onDisconnected Device disconnected: ' + disconnectedDevice.id);
});

onDisconnected should fire when disconnect occures.

### Current Behavior

onDisconnected callback is never called on Android devices.

*iOS is working. Tested with iPhone XS.*

### Library version

3.1.0

### Device

Android at least 9 and 12 tested

### Relevant log output

```shell
Only catch I got is from monitor characteristics:
monitorCharacteristicForDevice catch [BleError: Device AB:BC:DD:EF:12:34 was disconnected] Disconnected from MAC='XX:XX:XX:XX:XX:XX' with status 8 (GATT_INSUF_AUTHORIZATION or GATT_CONN_TIMEOUT)
```

### Additional information

Worked on 2.x.x versions.

Is this working on other users on 3.1.0? Please.

**Comment by andycamp** [comment]
I can confirm we are experiencing the same issue with onDisconnect it never called on android, but it's called on ios.

**Comment by andycamp** [comment]
We have also seen this issue on 3.0.0. Works fine on 2.x.x versions.

**Comment by cyberdevnet** [comment]
same here

**Comment by lucas-bortoli** [comment]
I'm having the same issue. The callback is never called with version 3.0.0 on Android.

**Comment by simonitfi** [comment]
Yes the library version 3.x is at the moment pretty useless until these critical bugs are fixed.

**Comment by dominik-czupryna-withintent** [comment]
Yes, the error has been confirmed, it occurs when disconnection occurs for a reason other than calling `disconnect` from `BleManager` (like Device side disconnect). And it's probably related to https://github.com/dotintent/react-native-ble-plx/issues/1103 . We are currently looking for a solution to the problem.

**Comment by dominik-czupryna-withintent** [comment]
Hi, we have changed the trigger of the disconnect action and released an RC version (https://www.npmjs.com/package/react-native-ble-plx/v/3.1.2-rc.0), could you check in your cases whether the change solves your problem?

**Comment by andycamp** [comment]
onDisconnect is triggered for us on the rc version.

**Comment by agutierrezgit** [comment]
Hi @dominik-czupryna-withintent - I was having this issue and at least in my case the RC version fixed it. Thanks a lot

**Comment by lucas-bortoli** [comment]
@dominik-czupryna-withintent  The RC version fixed the problem. The onDisconnected callback is now triggering when the peripheral device disconnects. Thanks a lot!

**Comment by simonitfi** [comment]
Also I could confirm that with quick tests I have done the onDisconnected callback is now triggering.

**Comment by angelos3lex** [comment]
So far so good for us too.
