### ISSUE TITLE
The invocation of setState within the startDeviceScan callback results in undesirable behavior on iOS devices🐛 

### ISSUE THREAD

**Issue by jogyfelix** [dotintent/react-native-ble-plx#1147]
### Prerequisites

- [X] I checked the documentation and FAQ without finding a solution
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

The startDeviceScan callback's output should remain unaffected by the selected storage mechanism

### Current Behavior

An issue occurs on iOS devices where the startDeviceScan callback function ceases to function after the first device details are returned. This behavior is observed only on iOS devices, and specifically on iOS 17.1.1 and Xcode 15.0.1. The problem arises when the setState method is invoked within the startDeviceScan callback. After the initial callback execution, subsequent invocations fail to produce any results.

### Library version

3.1.2-rc.0

### Device

iPhone XR, iOS 17.1.1

### Environment info

```shell
System:
  OS: macOS 14.1.1
  CPU: (8) arm64 Apple M1
  Memory: 139.56 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.10.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.yarn/bin/yarn
  npm:
    version: 8.19.2
    path: /opt/homebrew/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.11.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.11005911
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.15
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.7
    wanted: 0.72.7
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

1. Defining a state variable and updating it within the scan function callback triggers an issue.
2. Commenting out the state update code resolves the problem, indicating that the issue is specifically related to state updates within the scan function callback.

### Formatted code sample or link to a repository

```js
const manager = new BleManager();
const [dev, setDev] = useState();

  useEffect(() => {
    startSearch();
  }, []);

  const startSearch = () => {
    manager.startDeviceScan(null, null, (error, device) => {
      if (error == null) {
        if (device?.name !== null) {
          if (
            device?.name.startsWith('Movesense') ||
            device?.name.startsWith('Nonin')
          ) {
            console.log(device?.name); // The console only functions once, halting after the first device detection
            setDev(device?.name); // Commenting out this line resolves the issue and restores normal operation.
          }
        }
      }
    });
  };
```

### Relevant log output

```shell
[RxBLEKit|DEBG|16:25:12.135]: CentralManager(10781498880) scanForPeripherals(
withServices: nil,
options: Optional([:]))
[RxBLEKit|DEBG|16:25:13.076]: CentralManager(10781476896) didUpdateState(state: poweredOn)

// after commenting out the state update
[RxBLEKit|DEBG|16:27:18.152]: CentralManager(10777707776) scanForPeripherals(
withServices: nil,
options: Optional([:]))
```

### Additional information

The functionality of the code was verified on Android devices and earlier iOS versions without any issues. However, upon updating to iOS 17 and Xcode 15, error began to occur.

**Comment by ioss** [comment]
I think you are creating a new BleManager. Your setState, will rerender the component. 
Move the manager out of the render function.
