### ISSUE TITLE
Handle Raw Data in notification

### ISSUE THREAD

**Issue by Viswa1999** [dotintent/react-native-ble-plx#1166]
### Prerequisites

- [X] I checked the documentation and FAQ without finding a solution
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm sure that question is related to the library itself and not Bluetooth Low Energy or Classic in general. If that so, please post your question on [StackOverflow](https://stackoverflow.com/questions/tagged/react-native-ble-plx?sort=active).
- [X] I'm running the latest version

### Question

I'm running a React Native with ble-plx library. For handling a large amount of data through notification with a time interval of 5 milliseconds is not possible. Here is the question, How to handle the large amount of data in ble-plx? Should I change anything in the libraries? How can I get the data in the time interval of 5 ms in React native?

**Comment by dominik-czupryna-withintent** [comment]
Does your device use Indications or Notifications? This question is quite complicated because with Notifications it is possible to lose data. It is possible that the queue on your device is overflowing.

**Comment by intent-kacper-cyranowski** [comment]
Hi @Viswa1999 
Do you still need help with the issue?

**Comment by laxminarayana-capgemini** [comment]
Hi @intent-kacper-cyranowski,
No, Thanks. I have already completed the Notification part
