### ISSUE TITLE
[IOS]  ERROR  Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.

### ISSUE THREAD

**Issue by george-eucare** [dotintent/react-native-ble-plx#1173]
### Prerequisites

- [X] I checked the documentation and FAQ without finding a solution
- [X] I checked to make sure that this issue has not already been filed

### Library version

3.1.2

### Platform

IOS

### Setup Description
1. Set up the project according to the official React Native documentation.->
 https://reactnative.dev/docs/environment-setup
2. install `react-native-ble-plx`
3. `new BleManager()` in project.
4. Get `ERROR Invariant Violation:  new NativeEventEmitter()  requires a non-null argument.` 

The error occurs only on iOS (Simulator and TestFlight App); Android is working good.

### Steps to Reproduce

``` jsx
import { BleError, BleManager, Characteristic, Device } from 'react-native-ble-plx';

const useBLE = () => {
  const bleManager =  new BleManager();
  
  return {
    ...
  };
}

export default useBLE;

```

### Relevant log output

```shell
`ERROR  Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.`
```

### Contents of the `package.json` file
{
  "name": "AwesomeProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "react": "18.2.0",
    "react-native": "0.73.4",
    "react-native-ble-plx": "^3.1.2"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "0.73.21",
    "@react-native/eslint-config": "0.73.2",
    "@react-native/metro-config": "0.73.5",
    "@react-native/typescript-config": "0.73.1",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-test-renderer": "18.2.0",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  }
}

info.plist:
```
<key>NSBluetoothPeripheralUsageDescription</key>
<key>NSLocationAlwaysUsageDescription</key>
```
### Additional Information

Android is working good.

already try `pod install` and `npm install`

**Comment by EmmaZachara** [comment]
Hi @george-eucare, 
Thanks for reaching out. We will verify the issue and get back to you soon.

**Comment by dominik-czupryna-withintent** [comment]
I tried to reproduce this problem but I am unable to get this error. I have generated an application and implemented basic device scanning and I do not see this error in any build. Would you be able to enable this project (https://github.com/dominik-czupryna-withintent/ble-plx-issues-1173) and confirm what exact steps I need to take to get the error?

BTW in 
```js
import { BleError, BleManager, Characteristic, Device } from 'react-native-ble-plx';

const useBLE = () => {
  const bleManager =  new BleManager();
  
  return {
    ...
  };
}

export default useBLE;
```
you shouldn't declare new BleManager() in lifecycle. You should have single instance of BleManager.

**Comment by george-eucare** [comment]
The error has not occurred again; 
it seems like the xcode cache wasn't cleared.  (product -> clean build Folder)
Thank you for your answer!

**Comment by LXCGH** [comment]
cd /Users/edy/luxiaochen/study/toystoreApp/ios
rm -rf Pods
rm -rf build
pod install
