### ISSUE TITLE
🐛 iOS example app does not want to start

### ISSUE THREAD

**Issue by kacper-szewczyk** [dotintent/react-native-ble-plx#1211]
### Prerequisites

- [X] I checked the documentation and FAQ without finding a solution
- [X] I checked to make sure that this issue has not already been filed

### Expected Behavior

Typing `react-native run-ios` should run ios version of example

### Current Behavior

react-native run-ios
(node:72636) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info Found Xcode workspace "BlePlxExample.xcworkspace"
info Found booted iPhone SE (3rd generation)
info Building (using "xcodebuild -workspace BlePlxExample.xcworkspace -configuration Debug -scheme BlePlxExample -destination id=E1C57F89-CC46-45AC-B921-E496563DFA33")

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 

error Failed to build ios project. "xcodebuild" exited with error code '65'. To debug build logs further, consider building your app with Xcode.app, by opening 'BlePlxExample.xcworkspace'.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace BlePlxExample.xcworkspace -configuration Debug -scheme BlePlxExample -destination id=E1C57F89-CC46-45AC-B921-E496563DFA33

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

### Library version

3.2.0

### Device

iOS

### Environment info

```shell
---
```

### Steps to reproduce

1. git clone latest version
2. npm install in main folder
3. npm install in example folder
4. pod install in example/ios
5. npm run ios

### Formatted code sample or link to a repository

```js
https://github.com/dotintent/react-native-ble-plx
```

### Relevant log output

```shell
react-native run-ios
(node:72636) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info Found Xcode workspace "BlePlxExample.xcworkspace"
info Found booted iPhone SE (3rd generation)
info Building (using "xcodebuild -workspace BlePlxExample.xcworkspace -configuration Debug -scheme BlePlxExample -destination id=E1C57F89-CC46-45AC-B921-E496563DFA33")

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 

error Failed to build ios project. "xcodebuild" exited with error code '65'. To debug build logs further, consider building your app with Xcode.app, by opening 'BlePlxExample.xcworkspace'.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace BlePlxExample.xcworkspace -configuration Debug -scheme BlePlxExample -destination id=E1C57F89-CC46-45AC-B921-E496563DFA33

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

Prepare packages

ComputeTargetDependencyGraph
...



The following build commands failed:
	PhaseScriptExecution [CP-User]\ [Hermes]\ Replace\ Hermes\ for\ the\ right\ configuration,\ if\ needed /Users/kszewczyk/Library/Developer/Xcode/DerivedData/BlePlxExample-euyuystoqfprngeuczkyqazkryyq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/hermes-engine.build/Script-46EB2E00015930.sh (in target 'hermes-engine' from project 'Pods')
(1 failure)
```

**Comment by madej10** [comment]
Thanks for bringing this to our attention. We'll look into it as soon as we get the chance 🙏
