### ISSUE TITLE
I have connected to the IoT device, but I still cannot get the data sent by the IoT device. Does it not support the Bluetooth serial port?

### ISSUE THREAD

**Issue by 2096406288** [dotintent/react-native-ble-plx#1224]
I have connected to the IoT device, but I still cannot get the data sent by the IoT device. Does it not support the Bluetooth serial port?

**Comment by intent-kacper-cyranowski** [comment]
Hi @2096406288 
It’s BLE library and because of that is using GATT to communicate, so you won’t be able to use other bluetooth profiles for communication.

**Comment by 2096406288** [comment]
好吧，。。。。。
