### ISSUE TITLE
How can i use this package to emitter beacons

### ISSUE THREAD

**Issue by rodrigodiasf1984** [dotintent/react-native-ble-plx#1235]
### Prerequisites

- [X] I checked the documentation and FAQ without finding a solution
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm sure that question is related to the library itself and not Bluetooth Low Energy or Classic in general. If that so, please post your question on [StackOverflow](https://stackoverflow.com/questions/tagged/react-native-ble-plx?sort=active).
- [X] I'm running the latest version

### Question

Hi guys, I'm working on a react-native project, in the project I need to emit beacons to an IOT device, how can I do this? 

I appreciate any help you can provide.

**Comment by intent-kacper-cyranowski** [comment]
Hi @rodrigodiasf1984 

According to the information in the [wiki](https://github.com/dotintent/react-native-ble-plx/wiki/=-FAQ:-Beacons), this library does not support beacons.
