### ISSUE TITLE
How to get connected device list 

### ISSUE THREAD

**Issue by MAYILERUMPERUMAL** [dotintent/react-native-ble-plx#1258]
### Prerequisites

- [X] I checked the documentation and FAQ without finding a solution
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm sure that question is related to the library itself and not Bluetooth Low Energy or Classic in general. If that so, please post your question on [StackOverflow](https://stackoverflow.com/questions/tagged/react-native-ble-plx?sort=active).
- [x] I'm running the latest version

### Question

How to get connected device list in app background bluetooth is connected and then inside app how to get connected device list

**Comment by aliberski** [comment]
@MAYILERUMPERUMAL https://github.com/dotintent/react-native-ble-plx/wiki/Bluetooth-Scanning
