### ISSUE TITLE
[iOS] Add connection parameters functionality

### ISSUE THREAD

**Issue by kompost** [dotintent/react-native-ble-plx#134]
Hey

I need to set my own connection interval, but it seems there is no such option. This is from the documentation, where I assume the PPCP is set:
"ConnectionOptions
Connection specific options to be passed before connection happen. [Not used]"
How can I get around this issue?

**Comment by Cierpliwy** [comment]
I have never seen iOS or Android API which would allow you to set PPCP of BLE connection. Can you send me a link to documentation which describes that?

**Comment by kompost** [comment]
Hmm, 
Long story short I need to update a characteristic at 100hz, or as close as possible. Basically if I don't set any connection parameters the bluetooth crashes. There is an app for bluetooth inspection called nRF Connect and in that app it is possible to set PPCP. See the attached picture.
![ble](https://user-images.githubusercontent.com/3822747/29983336-9eacca58-8f55-11e7-81ae-9f1941fe0064.png)
If it is set on high my app runs without crashing and sending all the data. I assume thats PPCP that is set there or am I missunderstanding something?

**Comment by dariuszseweryn** [comment]
On Android the function for this functionality is named `BluetoothGatt.requestConnectionPriority(int)`. It is available on the level of `RxAndroidBle` underneath starting from API 21.

I am not sure if iOS does allow to change these settings which may be a problem to implement a function on the `react-native-ble-plx` level that would work the same on both platforms. Moreover iOS does not allow for Connection Intervals shorter than 30 ms if I am not mistaken.

An additional problem on Android is a bit of inconsistency of what exact parameters you would get by requesting a specific priority on different OS versions.

The best idea would be to alter the firmware of your peripheral to manage the connection parameters as from the peripheral side one would get most control over the procedure.

Best Regards

**Comment by JBaczuk** [comment]
@dariuszseweryn It appears this might be the API on iOS to change the connection interval:

https://developer.apple.com/documentation/corebluetooth/cbperipheralmanager/1393277-setdesiredconnectionlatency

If so, how would one go about implementing this in the library?

**Comment by dariuszseweryn** [comment]
This actually looks like it could be doable now. I will mark this issue as a feature request.

**Comment by lifekaizen** [comment]
> @dariuszseweryn It appears this might be the API on iOS to change the connection interval:
> https://developer.apple.com/documentation/corebluetooth/cbperipheralmanager/1393277-setdesiredconnectionlatency

Note that this method says: `When you call this method ... connection latency changes aren’t guaranteed. `

**Comment by abursztynowska** [comment]
I'm excited to inform you that we've released a new version of `react-native-ble-plx`. Many of the concerns and bugs have been addressed in this update.

If you encounter any issues or have further suggestions, please don't hesitate to open a new issue.

**Comment by lcrodrigues** [comment]
@abursztynowska is there any way to change the connection interval in the new version of `react-native-ble-plx`?
