### ISSUE TITLE
Feature Request: Add support for new iOS 13 bluetooth permission/authorization feature

### ISSUE THREAD

**Issue by bitcrumb** [dotintent/react-native-ble-plx#518]
## Current Behavior

* The library properly emits an "unauthorized" state when the user is not allowed to use bluetooth. 
  * However there is no way to determine through the library what the *reason* for this unauthorized state is. In iOS 13 the user can explicitly deny or approve bluetooth permission, since a dialog will be displayed by default for all new, updated *and* existing apps.

## New behavior

There should be a way to check the authorization status (via [CBManagerAuthorization](https://developer.apple.com/documentation/corebluetooth/cbmanagerauthorization?language=objc)) when bluetooth manager reports the "unauthorized" state to determine of a user denied the permission or not (and allow us to act accordingly in the UI).

**Comment by ultimate5289** [comment]
I also experienced the same issue on iOS 13

**Comment by ntrannghia** [comment]
I also experienced the same issue on iOS 13

**Comment by ntrannghia** [comment]
hi @bitcrumb, I found out that BleManager.onStateChange can emit "Unauthorized" status

**Comment by bitcrumb** [comment]
@ntrannghia Yes, that's what I explained in my issue. I rephrased a bit to make this more clear. What I *am* talking about however, is that there is no way to retrieve the reason for this "unauthorized" state. This is communicated through a a new API availablein iOS 13. The CBManagerAuthorization enum. This part has not been incorporated yet.

Also, the current version of ble-plx does not compile on the beta Xcode 11.

**Comment by RWOverdijk** [comment]
@bitcrumb Yes, I notice the same.

> node_modules/react-native-ble-plx/ios/RxBluetoothKit/RxCBPeripheral.swift:364:121: 'canSendWriteWithoutResponse' is only available in iOS 11.0 or newer

**Comment by bitcrumb** [comment]
There's a PR opened that presumably fixes this: https://github.com/Polidea/react-native-ble-plx/pull/527

**Comment by bitcrumb** [comment]
Yes idd, I noticed that the PR has merged. Thanks for that :)
I think the only thing that remains now is indeed to have access to the enum containing the reason for being unauthorised to use bluetooth. This can come in handy to display certain specific UI/feedback to the user.
