### ISSUE TITLE
Potential memory leaks on multiple calls to BleManager constructor

### ISSUE THREAD

**Issue by mikolak** [dotintent/react-native-ble-plx#767]
Each time BleManager is created the `createClient()` function is called, which creates a new instance of the MBA/native clients for interacting with OS BT stack. This method does not check whether a client is already existing, it just creates a new one, always. Additionally it diminishes the benefit of having the state live in the native code which is not reloaded, because the application loses access to it. 

One case where the leak might occur is full JS reload (as opposed to hot reload) while debugging.

I think of two plausible scenarios for finding it. The base is to start an operation that is emitting events, as all clients will use the same instance of the module to transmit those.

Prerequisite:
1. Create BleManager instance.
2. Connect to a device and run discovery
3. Setup notifications on a characteristic X

Scenario 1 - reloading:

0. Modify the library to log all notifications (before applying filtering to listeners)
1. _prerequisite with characteristic A_
2. Reload app from debug menu
3. _prerequisite with characteristic B_

Scenario 2 - creating multiple managers:

0. Modify the library to log all notifications (before applying filtering to listeners)
1. _prerequisite with characteristic A_
3. _prerequisite with characteristic B_

We should receive notifications from both characteristic, even though the client corresponding to characteristic A is no longer accessible to JS.

If the leak does occur, we can resolve it by either destroying the old client after receiving the call to create a new one OR ignoring the call if a valid client exists. In case we decided on the first solution, we should clean up any ongoing operations, which might be harder.

**Comment by abursztynowska** [comment]
I'm excited to inform you that we've released a new version of `react-native-ble-plx`. Many of the concerns and bugs have been addressed in this update.

If you encounter any issues or have further suggestions, please don't hesitate to open a new issue.
