### ISSUE TITLE
Question: How to correctly config the Location Permission for Android? (Google Play 2021)

### ISSUE THREAD

**Issue by rmtry** [dotintent/react-native-ble-plx#830]
Hi,

I am having a problem with publishing the app on Google Play Store:

```
Hi Developers, we found that your app is not compliant with one or more of our Developer Program Policies. See below for more information about your app’s status and how to correct the issue

**Issue with your app**
--
We’ve reviewed your app for compliance with all Location Permissions policy requirements (including use case eligibility), and found the following issues with your app:Missing information in prominent disclosure

**About the Permissions & Location Permissions policies**
--
You may only request permissions that are necessary to implement critical current features or services in your application. You may not use permissions that give access to user or device data for undisclosed, unimplemented, or disallowed features or purposes. In order for our team to check for compliance, we must be able to review and verify your in-app experience.


```
As far as I understand, there are 3 things to be considered: permissions declared in AndroidManifest.xml, alerting permission request to user and enable Permission method.

I wonder which is the best way to implement the last 2 steps? Currently, I am using ```
PermissionsAndroid.check(
      PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION
    )
``` to check for permission and ```
PermissionsAndroid.request(
                PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION
              )
``` to request the user or user can go to Settings location and enable manually through `Linking.openSettings()`.

Thanks all

**Comment by Krizzu** [comment]
This question is not specific to this library, but rather compliance with new G policy.

What you're being asked specifically is explicitness - you need to notify user why and how you're going to use the background data. In my case, I created a special screen that explains how/why data will be used with a button that activates permission request. [It follows the guide provided by Google for that case.](https://support.google.com/googleplay/android-developer/answer/9799150?hl=en#zippy=%2Cstep-provide-prominent-in-app-disclosure)

You can also send a video explaining the in-app usage of the location data, to make help Google review your app.
More info can be found here: [](url)

**Comment by JTend** [comment]
Where do I find this AndroidManifest.xml ?????
