### ISSUE TITLE
[ANDROID] Bluetooth scan doesn't triggered on background

### ISSUE THREAD

**Issue by ezranbayantemur** [dotintent/react-native-ble-plx#848]
Hi there. I'm trying to use this package for background scanning, connecting and sending commands to ble sensors. It works well but I can't trigger bluetooth scan on background.

Basically I'm trying to restarting the bluetooth scan when / if the connection process throws an exception (_device disconnects, discovering services blocked, etc.._) but it doesn't find any device.

**Example code is:**
```js
  const backgroundTask = async () => {
    await new Promise(async () => {
      startScan();
      await wait(5000);

      // Let's say error happened right now and,
      manager.stopDeviceScan();
      await wait(5000);

      // we trying to restart
      startScan();
    });
  };

  const startScan = () => {
    manager.startDeviceScan(
      [UUIDS.SCAN],
      {scanMode: ScanMode.LowPower},
      (err, device) => {
        err && console.log(err);
        device && console.log(device.id);
      },
    );
  };
```

Main thing is when I check the bluetooth log with adb; looks like it's restarting the scanning. I can found it as ongoing scan but I can find any device. 

**ADB Output**
```
  com.<package name> (Registered) (Filtered)
  LE scans (started/stopped)         : 2 / 1
  Scan time in ms (min/max/avg/total): 5029 / 22655 / 13842 / 27684
  Total number of results            : 1
  Last 1 scans                       :
    05-20 12:46:19 - 5029ms Filter 1 results (7)
  Ongoing scans                      :
    05-20 12:46:29 - 22655ms Filter 0 results (6)
  Application ID                     : 6
  UUID                               : 98becdfa-bda5-4868-8f39-b8357ccbb30c
  Connections: 0
```
There is not any error or something on logcat.

By the way I'm using the [react-native-background-actions](https://github.com/Rapsssito/react-native-background-actions) for background task but I don't think the issue related to it.

Any thoughts about it?

**Comment by santiagomartinez** [comment]
In case you are running on Android 10+:
BT requires location services enabled to work. On Android 10+ background location permission was added so to make it work in background I had to add ACCESS_BACKGROUND_LOCATION in AndroidManifest.xml to make it work.
It is not stated in the official Android documentation [link](https://developer.android.com/training/location/permissions#background) but that seems to be the solution [link](https://stackoverflow.com/questions/58059097/altbeacon-stopped-working-on-android10-and-didenterregion-does-not-get-called-at)
