### ISSUE TITLE
How can one restart the library/stack with a similar effect to killing and restarting the app?

### ISSUE THREAD

**Issue by hugows** [dotintent/react-native-ble-plx#854]
Hello friends,

first thanks for this wonderful library - its mostly a breeze for me and working with iOS and Android properly.

What happens to me now that more people are using my apps and sometimes we hit reliability issues - for example, in some devices in some situations, users just click all around frantically... and the app just stops scanning properly. (Of course this can also be just logic on the app side- but this happens regularly and in different apps..) 

What I usually do in those times is to "kill" the app, which always works but I can't really ask users to do.

**Is there any way to achieve a similar behaviour without closing the app ? I tried closing and opening the BLE manager but that didn't seem to trigger a low level restart.**

Thanks in advance!

**Comment by abursztynowska** [comment]
I'm excited to inform you that we've released a new version of `react-native-ble-plx`. Many of the concerns and bugs have been addressed in this update.

If you encounter any issues or have further suggestions, please don't hesitate to open a new issue.
