### ISSUE TITLE
How to pair bluetooth devices programatically without user interaction using react-native-ble-plx?

### ISSUE THREAD

**Issue by aarthigovardhanan88** [dotintent/react-native-ble-plx#855]
## Question

I am trying to implement a Bluetooth pairing programatically between a device and mobile app. I am able to pair the device but the problem is that it requires user to enter the passcode which I don't want in my app. I want to do that programatically. I need to provide the device name and the passcode programatically. I am using the library react-native-ble-plx. I could not find documentations related to this in the library.

Is this possible with the current version of the library?

**Comment by ezranbayantemur** [comment]
What you mean passcode? Should you write it to device characteristic?

**Comment by aarthigovardhanan88** [comment]
No, Passcode/password used for pairing

**Comment by ezranbayantemur** [comment]
You can create a modal which is contains a TextInput for asking user to enter PIN and then you can let the user pair the device.

And plus, it's not a bug or a issue of this package. I suggest you to ask these kind of code questions to StackOverflow. Not here.

**Comment by etruscanarcher** [comment]
How did you solve this problem? Can you specify it?
