### ISSUE TITLE
Can't read same characteristic in iPad while i can read in iPhone

### ISSUE THREAD

**Issue by serdargun** [dotintent/react-native-ble-plx#856]
Hi! I am trying to read following characteristic with `readCharacteristicForDevice`.

```
id: 10747871424
uuid: "0000ffa6-0000-1000-8000-00805f9b34fb"
isNotifiable: true
isNotifying: false
isReadable: false
isWritableWithResponse: false
serviceID: 10795325248
value: null
isIndicatable: false
serviceUUID: "0000ffa0-0000-1000-8000-00805f9b34fb"
deviceID: "8520226C-F25F-05EE-85FD-1E75A5804674"
isWritableWithoutResponse: false
```

 You see this characteristic has `isReadable: false` property. But I can read this characteristic in iPhone. I have no problem with that because I already need to read this characteristic. The problem is I can't read same characteristic in iPad. I am getting following error.

`
BleError: Characteristic 0000ffa6-0000-1000-8000-00805f9b34fb read failed for device E8915B50-12D4-79A8-8F60-C0F924ED9938 and service 0000ffa0-0000-1000-8000-00805f9b34fb`

Now I have two questions:

1. If this characteristic has `isReadable: false` property, why can I read this in iPhone?
2. While I read same characteristic in iPhone, why can't I read in iPad?

If I have misunderstanding on anything, sorry about that.

**Comment by abursztynowska** [comment]
I'm excited to inform you that we've released a new version of `react-native-ble-plx`. Many of the concerns and bugs have been addressed in this update.

If you encounter any issues or have further suggestions, please don't hesitate to open a new issue.
