### ISSUE TITLE
Question: Is the "operation timeout" configurable?

### ISSUE THREAD

**Issue by amduffy19** [dotintent/react-native-ble-plx#862]
Occasionally when I try to read RSSI it times out with an "operation timed out" error. I'm still trying to find the cause, but in the meantime I was wondering if this operation timeout was configurable? I'd like to time out more quickly and just try again. Thank you!

**Comment by james1050** [comment]
I don't think this is configurable. However, I had an issue where often reading RSSI of multiple devices would result in at least one readRSSI() call timing out. At the time I was firing off each readRSSI within promises so they'd be asynchronous. Once I changed to calling readRSSI() synchronously (waiting for each read) there were no more timeouts.
