### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by goofiw** [dotintent/react-native-ble-plx#864]
The docs page is down.

https://polidea.github.io/react-native-ble-plx/

**Comment by serdargun** [comment]
You can use following link:

https://dotintent.github.io/react-native-ble-plx/

**Comment by mciechanowicz** [comment]
Hi,

It was already changed in readme 😉
This is actual link to documentation: [documentation](https://dotintent.github.io/react-native-ble-plx/)
