### ISSUE TITLE
throw error in monitorChracteristicForDevice()

### ISSUE THREAD

**Issue by zorba0517** [dotintent/react-native-ble-plx#878]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### I wanted to catch err created in function named "monitorCharacteristicForDevice" on another file that call the function.
![스크린샷 2021-07-08 오후 2 06 24](https://user-images.githubusercontent.com/84304192/124866472-6cc99b00-dff7-11eb-93b5-a5dc33165ac7.png)

### the function is being called from below.
![스크린샷 2021-07-08 오후 2 09 44](https://user-images.githubusercontent.com/84304192/124866593-a0a4c080-dff7-11eb-8e89-5e498aa84129.png)

### But, i could not the err catch at all. but only  err message i could get is below.
![스크린샷 2021-07-08 오후 2 17 24](https://user-images.githubusercontent.com/84304192/124866573-92ef3b00-dff7-11eb-8487-b6ad6bba6e63.png)

## Context

```
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 113.73 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.3.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.15.1 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 27, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^5.0.1-alpha.2 => 5.0.1 
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by dominik-czupryna-withintent** [comment]
The new major release updates the core packages that support the latest versions of the operating system and fixes some old bugs. Please confirm if the issue still persists and create a new issue if it still does.
