### ISSUE TITLE
Link to documentation in README.md is broken

### ISSUE THREAD

**Issue by Jurpp** [dotintent/react-native-ble-plx#882]
## Expected Behavior

Link in the README points towards : https://dotintent.github.io/react-native-ble-plx/

## Current Behavior

Link in the README points towards : https://polidea.github.io/react-native-ble-plx/

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Go to the [documentation section in the README](https://github.com/dotintent/react-native-ble-plx#documentation--support).
2. Click on "Documentation can be found here."
3. Observe 404

**Comment by Jurpp** [comment]
This is actually a duplicate of #867

**Comment by mciechanowicz** [comment]
Hi,

This is actual link to documentation: [documentation](https://dotintent.github.io/react-native-ble-plx/)
