### ISSUE TITLE
writeCharacteristicWithoutResponseForDevice for a device which is not advertise its serviceuuids 

### ISSUE THREAD

**Issue by rt012** [dotintent/react-native-ble-plx#883]
Why it isn't possible that you can write to a device if the field serviceUUIDs is empty but the device.services() method returns services. 

I found the responsible code: 
https://github.com/dotintent/MultiPlatformBleAdapter/blob/master/android/library/src/main/java/com/polidea/multiplatformbleadapter/BleModule.java
BLEModule => getCharacteristicOrEmitError

   final Service service = device.getServiceByUUID(UUIDs[0]);
        if (service == null) {
            onErrorCallback.onError(BleErrorUtils.serviceNotFound(serviceUUID));
            return null;
        }

How i connect and discover the device: 

` connectToDevice(deviceUUIDorMac: string): Promise<IBleConnectedDevice> {
    return new Promise((resolve, reject) => {
      return this.manager.connectToDevice(deviceUUIDorMac)
        .then((device) => {

          console.log(device);
          return this.manager.discoverAllServicesAndCharacteristicsForDevice(deviceUUIDorMac)
            .then(async (d) => {
              return resolve(d);
            });
        })
        .catch((err) => {
          reject(err);
        })
    })
  }`

Edit: In the documentation I found: 

> Notes
device.serviceUUIDs and device.serviceData are related to BLE Scan Advertisement, not to Service Discovery. They will not be populated/updated in result of device.discoverAllServicesAndCharacteristics()

**Comment by abursztynowska** [comment]
I'm excited to inform you that we've released a new version of `react-native-ble-plx`. Many of the concerns and bugs have been addressed in this update.

If you encounter any issues or have further suggestions, please don't hesitate to open a new issue.
