### ISSUE TITLE
The link to "Documentation can be found here." is broken

### ISSUE THREAD

**Issue by williamgoodhew** [dotintent/react-native-ble-plx#885]
The link on the homepage to Documentation can be found here is broken. Please could you let me know where I find the latest documentation.

Thanks

**Comment by gretzky** [comment]
Duplicate of #882  #867 #866

**Comment by mciechanowicz** [comment]
Hi,

This is actual link to documentation: [docs](https://dotintent.github.io/react-native-ble-plx/)
