### ISSUE TITLE
Bug Report: Shows warning with React Native 0.65

### ISSUE THREAD

**Issue by Naturalclar** [dotintent/react-native-ble-plx#896]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

## Expected Behavior

Please describe the behavior you are expecting

Calling new BleManager in react-native 0.65 will not show any warning

## Current Behavior

What is the current behavior?

Calling new BleManager in react-native 0.65 shows the following warning

```
new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Use `react-native-ble-plx` in a project using react-native v0.65+ on an Android device.
2. Run `new BleManager()`

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Both JS and platform logs can be enabled via [setLogLevel](https://polidea.github.io/react-native-ble-plx/#blemanagersetloglevel) function call. 

* Library version: 2.0.2
* Platform: Android.
* Platform logs (logcat/XCode):
* JS logs: ``new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.`
* Contents of the `package.json` file:
	"react-native": "0.65.1",
    "react-native-ble-plx": "^2.0.2"
* Formatted code sample or link to a repository:

```js
const ble = new BleManager();
```

**Comment by uloco** [comment]
Will this affect behaviour of the ble library at the moment? I'm wondering if this is just a warning or if I should revert the upgrade of react-native now completely ...

I tried to understand what needs to be changed but not quite sure to be honest.
Basically the react-native eventemitter now needs to be constructed with an instance where the removeListeners function is required to be present on it.

See https://github.com/facebook/react-native/commit/114be1d2170bae2d29da749c07b45acf931e51e2

**Comment by Naturalclar** [comment]
@uloco 
honestly, I don't think it affects the behavior of this library at the moment.

a different react-native module just added a stub implementation off event listeners to prevent the warning, and I think this library can be applied the same way

ref: https://github.com/software-mansion/react-native-reanimated/pull/2316/files

**Comment by askie** [comment]
+1, the same bug

**Comment by mciechanowicz** [comment]
Hi,

@Naturalclar thanks for reporting the issue and fixing it. Your PR has been merged! 💪
