### ISSUE TITLE
Has this library been abandoned?

### ISSUE THREAD

**Issue by scinfu** [dotintent/react-native-ble-plx#910]
Has this library been abandoned?

**Comment by eds-snippets** [comment]
Our hardware specialist who is working with our bluetooth device directly looked at some libraries and found one which was recently updated: react-native-ble-manager (May 17th update). So he started to implement some example code on top of that. But I want to look around and maybe to find something else. We have no favorites here. Just want to use something what is not abandoned and at least works with our device.

**Comment by mciechanowicz** [comment]
Hi ✋ sorry for not replying sooner.
No, this library was not abandoned.

The owner of the library has changed, and it took some time for this to happen, so it may have looked like the library was abandoned, but it wasn't 😉

The doitnent team is dedicated to resolving existing issues and developing the library. 

Once again, we apologize and hope that you will continue to use the library 🚀

**Comment by ericschaal** [comment]
Hi @mciechanowicz looks like not much is happening here. Can you confirm that the dotintent team is dedicated to resolving existing issues and further developing the library as you said above?

**Comment by jamesrogers93** [comment]
No updates since Nov 2021, so looks like the library was never picked up by the new ownership? Unless I'm missing something
