### ISSUE TITLE
Project Setup: Running react-native and building ios fails due to errors in MultiplatforBleAdapter pod

### ISSUE THREAD

**Issue by Arnav-UofT** [dotintent/react-native-ble-plx#913]
- [ ] I am running the latest version
- Yes - 2.0.2
- [ ] I checked the documentation and found no answer
- Yes
- [ ] I checked to make sure that this issue has not already been filed
- Yes, I have tried to reach out to ios repos regarding this issue as well
- [ ] I followed every installation step mentioned in README file.
- Yes, my team confirms the errors indicate in logs that they are realted to rn - ble-plx

## Setup problem

Please describe the problem you are experiencing.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Init project in react native
2. install rn - ble-plx and import in any module
3. pod install 
4. command to build and run on ios simulator (any iPhone)

### Context

I am trying to run an organization repository (react native app on ios and Andriod). I have not tried android yet since I only have access to the ios simulator through xcode. My team is working on it but similar issue arised after recent install of this library for bluetooth com.

* Library version: X.Y.Z
* Platform: iOS
* Platform logs (logcat/XCode):
<img width="398" alt="Screen Shot 2021-10-25 at 12 50 59 PM" src="https://user-images.githubusercontent.com/56146362/138652645-cefd1c18-0380-413a-87bb-5f1d3dc62225.png">

* Contents of the `package.json` file:

**Comment by bkbooth** [comment]
@t3db0t's fix worked for me. I didn't need step 3 though, after yarn/npm install the podspec in `react-native-ble-plx` was already updated.

Also, you might want to reference a commit hash in your package.json dependency (e.g. `"react-native-ble-plx": "https://github.com/below/react-native-ble-plx#55ff5cb"`) Just in case more commits get added to that repo (nefarious or otherwise), you might not want to bring those into your repo too.

**Comment by jdeibe** [comment]
I'm getting ../node_modules/react-native-ble-plx/ios/Pods/Target Support Files/Pods-BleClient/Pods-BleClient.debug.xcconfig:1:1: unable to open file (in target "BleClient" in project "BleClient")
Any clues ?

**Comment by chakrihacker** [comment]
This is fixed with 2.0.3

This issue can be closed

**Comment by mciechanowicz** [comment]
Hi! It was fixed in the 2.0.3 release! 🔥

So I am closing this issue.
