### ISSUE TITLE
How do I disconnect from a device upon killing my app

### ISSUE THREAD

**Issue by dheadrick1618** [dotintent/react-native-ble-plx#916]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm sure that question is related to the library itself and not Bluetooth Low Energy or Classic in general.

It seems that whenever I have established a connection to our device with my phone, upon killing the app on my phone the device continues to think it is still connected with my phone, and upon scanning again after restarting the app, the device I would like to connect to does not show up and its 'connected' indicator led is still on. 

Is there a way (preferably without native code), where one can disconnect their phone from the connected device(s) upon the app being shutdown? 

My app is entirely functional and thus I cannot rely on placing disconnect code in a 'componentDidUnmount()' or anything along those lines. This being said I don't see how the device still thinks its connected to my phone when I close the app, shouldn't killing the BLEManager() instance kill the connection as well? I know its not my device as I have tested it with other terminal apps etc, and this behavior does not occur.

Thank you.

**Comment by andrewcharnley** [comment]
This is a real headache that needs fixing.

**Comment by andrewcharnley** [comment]
I did a bit more research on my own implementation. There's a deregister call not being made by this library to Androids BLE manager which keeps the app thread running on any exit from the App. When React (console) forces an App reload it kills it which works to disconnect it.

I can't see a means to force termination from inside the App so we need to work out what the deregistration call is and add it. I doubt it'll be difficult and will get round to it sometime in the next few weeks or so if nobody else does in the meanwhile.

**Comment by andrewcharnley** [comment]
Figured it out. Bad documentation and code but this will do it.

In my app I'm either connected (ret.device) or it's scanning. Call within the return on a useEffect within App.js so it run on exit.


 ``` try {
    if (ret.device) {
      try {
        const p = new Promise(()=>{}, ()=> {});
        manager.cancelDeviceConnection(ret.device.id, p);
        await p();
      } catch (e) {
      }
      delete ret.device;
    }
  } catch(e) {
    try {
      manager.stopDeviceScan();
    } catch (e) {
    }
  }
```

**Comment by andrewcharnley** [comment]
Doesn't work with React's hot load feature as it's not exiting the app. I need to figure out how to force that.

**Comment by Matheuschn** [comment]
@andrewcharnley, you may use React Native [AppState](https://reactnative.dev/docs/appstate), adding a listener to a change to the app state:

``` js
AppState.addEventListener('change', async (state) => {
     if (state !== 'active') {
          manager.cancelDeviceConnection(device.id);
     }
}
```

**Comment by mciechanowicz** [comment]
Hi. You can do it the way @Matheuschn showed it. Thanks to him for the answer 🔥

In case of problems, you can reopen this issue. Closing for now.
