### ISSUE TITLE
Graphing data from gps sensor with Arduino with react-native

### ISSUE THREAD

**Issue by Cans11** [dotintent/react-native-ble-plx#918]
Hello there. I made a connection to the arduino nano 33 ble sense card using the react-native-ble-plx library. There is a gps sensor connected to the development board and it can send some parameters to the phone right now. But I want to parse the data and show it on the screen in graphic form. how can I do that? I looked through the library files and the code. data is using separate service and characteristic uuid.

the source I got the sample from,
[https://github.com/Spoutnik97/react-native-arduino-ble-example](url)

**Comment by Cans11** [comment]
yes I'm taking it with ble. I don't know what to do next

**Comment by abursztynowska** [comment]
I'm excited to inform you that we've released a new version of `react-native-ble-plx`. Many of the concerns and bugs have been addressed in this update.

If you encounter any issues or have further suggestions, please don't hesitate to open a new issue.
