### ISSUE TITLE
the app crash

### ISSUE THREAD

**Issue by davild** [dotintent/react-native-ble-plx#919]
On the Xiaomi mobile phone MIUI 12 or above, the react native app performs a pin Bluetooth connection, or cancels the matching Bluetooth, and the app crashes

**Comment by AdamKobus** [comment]
Hello, could this potentially be related to the changes to permissions in Android 12? https://developer.android.com/guide/topics/connectivity/bluetooth/permissions
You would have to update your AndroidManifest.xml accordingly

**Comment by mciechanowicz** [comment]
I'm closing the task at the moment, if the answer was not enough, you can reopen it.

**Comment by sami-sy** [comment]
> https://developer.android.com/guide/topics/connectivity/bluetooth/permissions

I have the exact same issue in miui 13
