### ISSUE TITLE
react-native-ble-plx 2.0.3 error

### ISSUE THREAD

**Issue by xuyushiguang** [dotintent/react-native-ble-plx#921]
[!] CocoaPods could not find compatible versions for pod "MultiplatformBleAdapter":
  In Podfile:
    react-native-ble-plx (from `../node_modules/react-native-ble-plx`) was resolved to 2.0.3, which depends on
      MultiplatformBleAdapter (= 0.1.9)

None of your spec sources contain a spec satisfying the dependency: `MultiplatformBleAdapter (= 0.1.9)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by xuyushiguang** [comment]
who may help me?

**Comment by Etchelon** [comment]
I had a similar issue and changed `0.1.7` to `0.1.9` in Podfile.lock

**Comment by mciechanowicz** [comment]
Hi @xuyushiguang

I am sorry that you had a problem while using the library. It has already been resolved in this PR: https://github.com/dotintent/react-native-ble-plx/pull/928 and should be merged soon.

if you want to avoid this problem you can use the changes from the PR I pasted above, or just delete your Podfile.lock file and then try to install pods again 🙂
