### ISSUE TITLE
How i can get getBondedDevices AND unpairedDevices ?

### ISSUE THREAD

**Issue by deepakjsr7979** [dotintent/react-native-ble-plx#930]

**Comment by scope2229** [comment]
there is the `devices` method but that takes an argument of `deviceIdentifiers` which is pointless as we don't know the Identifiers. In the end I used react-native-ble-manager

**Comment by mciechanowicz** [comment]
Hi,
@deepakjsr7979 you can try with `devices(deviceIdentifiers: Array<DeviceId>)` or  `connectedDevices(serviceUUIDs)`
