### ISSUE TITLE
Scanning is stopped when app is in the background and screen is locked

### ISSUE THREAD

**Issue by IvKr95** [dotintent/react-native-ble-plx#947]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior

The app continues to fetch data from a BLE device even when the screen is locked and gone dark

## Current Behavior

No data passed to the app and no logs are visible in Logcat, but when the user presses the power button on their phone and sees a lock screen the process resumes.

* react-native-ble-plx: 2.0.3
* react: 17.0.2
* react-native: 0.65.1
* Platform: Android

**Comment by mciechanowicz** [comment]
Hi.

According to what is in the documentation: background mode is only supported for iOS devices.
