### ISSUE TITLE
getting null device name while calling startDeviceScan

### ISSUE THREAD

**Issue by scrapecoder** [dotintent/react-native-ble-plx#948]
const scanAndConnect = () => {
    bleManager.startDeviceScan(
      null,
      {allowDuplicates: false},
      (error, device) => {
        if (error) {
          if (error.message === 'BluetoothLE is powered off') {
            bleManager.enable();
          }
          // Handle error (scanning will be stopped automatically)
          return;
        }

        // Check if it is a device you are looking for based on advertisement data
        // or other criteria.

        if (device && device.name) {
          console.log('device name====>', device.name);
        }
        console.log('device-<', device);
      },
    );
    };

`"id":"40:1E:8E:D2:E5:7E",
    "isConnectable":null,
    "localName":null,
    "manufacturerData":"TAAQBUccC65x",
    "mtu":23,
    "name":null,
    "overflowServiceUUIDs":null,
    "rssi":-37,
    "serviceData":null,
    "serviceUUIDs":null,
    "solicitedServiceUUIDs":null,
    "txPowerLevel":null`

* Library version: '^2.3.0'
* Platform: Android.

**Comment by mciechanowicz** [comment]
HI,
can you use some external scanning application to see if the name is there or it is also null?

**Comment by mreda7** [comment]
Hi @scrapecoder , I have the same problem here . Did you find a solution for this ?

**Comment by Robiullah2244** [comment]
Same issue

**Comment by disconnect-ed** [comment]
Same issue

**Comment by yosukapro** [comment]
+1 android

**Comment by abhinavshm95** [comment]
+1 iOS

**Comment by iSaBo96** [comment]
+1 iOS

**Comment by abursztynowska** [comment]
I'm excited to inform you that we've released a new version of `react-native-ble-plx`. Many of the concerns and bugs have been addressed in this update.

If you encounter any issues or have further suggestions, please don't hesitate to open a new issue.

**Comment by dominik-czupryna-withintent** [comment]
We have added a scanning option for BT 5 advertisers (disable legacy scan - https://github.com/dotintent/react-native-ble-plx/wiki/Device-Bonding) and name mapping for Android.
