### ISSUE TITLE
Support for latst version of react native

### ISSUE THREAD

**Issue by feistyz** [dotintent/react-native-ble-plx#950]
Hi,

Is there a plan to support the latest version of react native, currently at version 0.67. If so when can we expect the update?

**Comment by mciechanowicz** [comment]
Hi,

There is already a pr with the upgrade of [RN version](https://github.com/dotintent/react-native-ble-plx/pull/925),  I hope it will be merged soon.

**Comment by feistyz** [comment]
Hi @mciechanowicz any update on this?
