### ISSUE TITLE
Not able to enable ccc descriptor

### ISSUE THREAD

**Issue by alok-shete** [dotintent/react-native-ble-plx#954]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior

Enable to cccd

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. connect the device by peripheral id
2. after connection using this connection object try to writeCharacteristicWithoutResponseForService for cccd

### Error 
```
 ble did update value for characteristic returned an error, : {"message":"Characteristic 00002902-0000-1000-8000-00805f9b34fb notify change failed for device ? and service 0000a002-0000-1000-8000-00805f9b34fb","errorCode":403,"attErrorCode":null,"iosErrorCode":null,"androidErrorCode":null,"reason":"Cannot write client characteristic config descriptor (code 3) with characteristic UUID 00002902-0000-1000-8000-00805f9b34fb","name":"BleError"}
```

### Context

I Want to enable ccc descriptor, but I'm unable to enable ccc descriptor
* Library version: 2.0.2
* Platform: Android
* JS logs: console log
* Formatted code sample or link to a repository:

```js
connectedDevice.writeCharacteristicWithoutResponseForService(
                    this.serviceId, // PLX SERVICE UUID,
                    "00002902-0000-1000-8000-00805f9b34fb", // PLX SPOTCHECK CCCD UUID,
                    Buffer.from([0x20]).toString("base64")
                  )
```

**Comment by dominik-czupryna-withintent** [comment]
The new major release updates the core packages that support the latest versions of the operating system and fixes some old bugs. Please confirm if the issue still persists and create a new issue if it still does.
