### ISSUE TITLE
Is react-native-ble-plx 2.0.3 supporting auto linking? If not can you please list what the steps are for manual linking?

### ISSUE THREAD

**Issue by adityareddyav** [dotintent/react-native-ble-plx#955]
Hello,

-  I am running the latest version `react-native-ble-plx` 2.0.3
- I checked the documentation and found no answer
- I checked to make sure that this issue has not already been filed
- I'm sure that question is related to the library itself and not Bluetooth Low Energy or Classic in general. Question has been already asked on StackOverflow but went unanswered - https://stackoverflow.com/questions/63787443/js-react-native-how-can-i-solve-this-error-for-building-react-native-app-for-i

## Question

- Is `react-native-ble-plx` 2.0.3 supporting auto linking?
- If it is not supporting auto linking, what are the steps for manual linking?

Below is the error message that I see on the Terminal - 

```
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
react-native-ble-plx (to unlink run: "react-native unlink react-native-ble-plx")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
```

**Comment by Matheuschn** [comment]
I'm pretty sure this library supports auto-linking. To solve your error, try unlinking the library as suggested in the message and running `npm install`. This should automatically link the library.

**Comment by abursztynowska** [comment]
I'm excited to inform you that we've released a new version of `react-native-ble-plx`. Many of the concerns and bugs have been addressed in this update.

If you encounter any issues or have further suggestions, please don't hesitate to open a new issue.
