### ISSUE TITLE
Android force kill doesn't disconnect

### ISSUE THREAD

**Issue by fgrs** [dotintent/react-native-ble-plx#957]
I know this was answered before and some suggested to use AppState/destroy solution but in my case I need characteristic data exchange also when app is in a background.

the actual issue occurs when my BT device uses fast mode and sends characteristics approx every 1 sec then if I swipe/kill the app the connection remains and from this point I can only power cycle BT device. If in normal mode (data approx every 3 sec) everything works fine and device disconnects perfectly.

I also noticed that leaving transaction id empty for monitorCharacteristicForService prevents BT device from disconnecting in both fast and normal mode which got me thinking that the initial issue is somehow related to transaction id.

Does anybody know how to get around this problem?

**Comment by Matheuschn** [comment]
Does this bug affect Android, iOS or both?

**Comment by fgrs** [comment]
I can confirm it only affects Android devices

**Comment by scsonic** [comment]
Too many android phone didn't implement BLE stack like Pixel/nexus phones.

**Comment by abursztynowska** [comment]
I'm excited to inform you that we've released a new version of `react-native-ble-plx`. Many of the concerns and bugs have been addressed in this update.

If you encounter any issues or have further suggestions, please don't hesitate to open a new issue.
