### ISSUE TITLE
got blocked when npm install helium

### ISSUE THREAD

**Issue by zhangyaobin** [dotintent/react-native-ble-plx#964]
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.github.Polidea:MultiPlatformBleAdapter:b0272c0fae040cc90f790481c54e8f2d45304339.
     Required by:
         project :app > project :react-native-ble-plx
      > Could not resolve com.github.Polidea:MultiPlatformBleAdapter:b0272c0fae040cc90f790481c54e8f2d45304339.
         > Could not get resource 'https://www.jitpack.io/com/github/Polidea/MultiPlatformBleAdapter/b0272c0fae040cc90f790481c54e8f2d45304339/MultiPlatformBleAdapter-b0272c0fae040cc90f790481c54e8f2d45304339.pom'.
            > Could not GET 'https://www.jitpack.io/com/github/Polidea/MultiPlatformBleAdapter/b0272c0fae040cc90f790481c54e8f2d45304339/MultiPlatformBleAdapter-b0272c0fae040cc90f790481c54e8f2d45304339.pom'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/6.9/userguide/build_environment.html#gradle_system_properties
                  > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by abursztynowska** [comment]
I'm excited to inform you that we've released a new version of `react-native-ble-plx`. Many of the concerns and bugs have been addressed in this update.

If you encounter any issues or have further suggestions, please don't hesitate to open a new issue.
