### ISSUE TITLE
How to obtain data from multiple manufacturers?

### ISSUE THREAD

**Issue by luhaimin** [dotintent/react-native-ble-plx#970]
Hi, I can receive two manufacturers' data in NRF app,
Why can't I get two broadcast data when I use startDeviceScan in react-native-ble-plx?
I want to know, how can I get the first broadcast data?

![image](https://user-images.githubusercontent.com/25789494/164714494-d6b52dbc-7a0e-457a-9907-aafd605f809d.png)

![image](https://user-images.githubusercontent.com/25789494/164715749-b71215c0-4fa1-41be-8bad-bd9dbd8d6beb.png)

Very urgent, looking forward to your answer

**Comment by wllamb** [comment]
Also having this issue, nRF Connect shows two different values for manufacturer data. I was able to get the correct one for awhile and all of sudden it's now giving me the opposite. Would be ideal if I could see both

**Comment by intent-kacper-cyranowski** [comment]
Hi @luhaimin and @wllamb 
Did `rawScanRecord` function solve your issues?

**Comment by intent-kacper-cyranowski** [comment]
I’m going to close the issue due to inactivity, in case of any problems feel free to open a new issue
