### ISSUE TITLE
Understanding long UUIDs

### ISSUE THREAD

**Issue by JamesOwen7** [dotintent/react-native-ble-plx#971]
Apologies if this is a stupid question. I'm very new to bluetooth as a whole.

I've connected my application to a glucose monitor. I'm trying to read that data - I've got the short UUIDs for the Glucose and then the characteristic Glucose Measurement. But these are in the form 0x1808 and 0X2A18.

Do I require the longer UUID? If so, how do I obtain this value?
Apreciate nany help!

**Comment by TusharAswalAexonic** [comment]
@JamesOwen7 were you able to do so? Please let me know how.
Thanks
