### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by luismiguelmena** [dotintent/react-native-ble-plx#976]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [ ] I'm sure that question is related to the library itself and not Bluetooth Low Energy or Classic in general. If that so, please post your question on [StackOverflow](https://stackoverflow.com/questions/tagged/react-native-ble-plx?sort=active) or on our [Gitter](https://gitter.im/RxBLELibraries/react-native-ble) channel.

## Question

Please describe the question.
I execute my code on a device with android studio and the scanner work correctly, but when I upload the app to the stores or generate an apk the scanner is not working.

**Comment by ibrahim-delice** [comment]
This sounds more like a bug rather than a question.
