### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by luismiguelmena** [dotintent/react-native-ble-plx#978]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior

Bluetooth scannning ok on devices

## Current Behavior

Right now is not scanning well in ios and android in apk but when I connect my device on my laptop and execute the scanner, it is working correctly

**Comment by dominik-czupryna-withintent** [comment]
The latest version (3.0.0) of the library has been tested in the release version and no error was found. Please confirm if the issue still persists and create a new issue if it still does.
