### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by luismiguelmena** [dotintent/react-native-ble-plx#979]
Android is not compiling, im getting the following error.
':react-native-ble-plx:compileDebugJavaWithJavac'

Build gradle:
ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        ndkVersion = "21.4.7075529"
    }

**Comment by dominik-czupryna-withintent** [comment]
The latest version (3.0.0) of the library has been tested in the compile release version and no error was found. Please confirm if the issue still persists and create a new issue if it still does.
