### ISSUE TITLE
Question - Does anyone know the minimum bluetooth version required for this project?

### ISSUE THREAD

**Issue by CaptainJeff** [dotintent/react-native-ble-plx#982]
## Question

Does anyone know the minimum Bluetooth version required to run this project? 4.0? 5.0? I read through the documentation and couldn't find anything.

**Comment by dominik-czupryna-withintent** [comment]
The library supports both versions, if you encounter any compatibility problems, feel free to open a new issue. Please note that for advertiser using the protocol version introduced in BT 5.0, the `legacyScan` variable must be set appropriately for Android (deviceshttps://dotintent.github.io/react-native-ble-plx/#connectionoptions)
