### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lochungtin** [dotintent/react-native-ble-plx#989]
## Question

Hi, I am currently building a bluetooth client for a device that uses the Object Transfer Protocol and I was wondering if the library supports the use of the L2CAP which is required by the OTS protocol.

Thanks.

**Comment by dominik-czupryna-withintent** [comment]
If I understand it correctly, it should be supported by the protocol on its own

![image](https://github.com/dotintent/react-native-ble-plx/assets/143402866/bf5c9d00-55a4-4fe4-8bbb-82b3e5f884ae)
https://www.bluetooth.org/docman/handlers/DownloadDoc.ashx?doc_id=309937

Did you have any problem with that? Are you able to provide an example?

**Comment by acouvreur** [comment]
Bumping this issue!

The current library does not allow the user to open an L2CAP CoC channel directly with the connected device.

The support could be added to the library.
