### ISSUE TITLE
Cannot connect to more than 3 peripherals at a time

### ISSUE THREAD

**Issue by zabojad** [dotintent/react-native-ble-plx#999]
My application uses `react-native-ble-plx` to connect to 4 very similar peripherals at a time. I recently crossed an issue with a specific device where I could not connect to more than 3. The 4th call to connect hangs and never returns.

The device is a JSN-L21, runs on Android 9 and supports Bluetooth 4.2.

My question is : How could I detect that a device does not support more than 3 BT connections at a time, so that I can manage that case nicely in the app?

**Comment by abursztynowska** [comment]
I'm excited to inform you that we've released a new version of `react-native-ble-plx`. Many of the concerns and bugs have been addressed in this update.

If you encounter any issues or have further suggestions, please don't hesitate to open a new issue.
